### ISSUE TITLE
Update Community page footer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#1]
The community page should list all the same resources as does layer5.io/meshery does.

The style of the community details do not need to match that of the layer5.io/meshery page. Buttons with fill onHover is not necessary.

**Comment by leecalcote** [comment]
Should look similar to this - 
<img width="299" alt="Screen Shot 2020-02-13 at 6 51 27 AM" src="https://user-images.githubusercontent.com/7570704/74437156-4cf76d00-4e2d-11ea-8cf0-4d53ce4137df.png">

**Comment by morrme** [comment]
@leecalcote looks like this can be closed 😄

**Comment by leecalcote** [comment]
Good eye! Yes.
