### ISSUE TITLE
Add GitHub stats to landing page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#103]
**Current Behavior**
Missing GitHub stats on landing page.

**Implementation**
Add the following stats in the section identified in the mockup.

- https://ghbtns.com/github-btn.html?user=layer5io&repo=meshery&type=star&count=true&size=large
- https://ghbtns.com/github-btn.html?user=layer5io&repo=meshery&type=watch&count=true&size=large&v=2
- https://ghbtns.com/github-btn.html?user=layer5io&repo=meshery&type=fork&count=true&size=large

<img width="1223" alt="Screen Shot 2020-02-13 at 11 23 12 AM" src="https://user-images.githubusercontent.com/7570704/74461062-85aa3d00-4e53-11ea-93ca-33101b5878d2.png">

**Comment by leecalcote** [comment]
@kanishkarj is this issue of interest to you?

**Comment by kanishkarj** [comment]
I could work on it.

**Comment by leecalcote** [comment]
Very good!

**Comment by kanishkarj** [comment]
Please checkout PR #105

**Comment by leecalcote** [comment]
Fixed by #105
