### ISSUE TITLE
Add a "Join the Community" button at the top of the Community page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#106]
**Current Behavior**
The project site should be prominently encouraging new community members. A "Join the Community" button will help with this as shown in the mockup below.

**Desired Behavior**
<img width="1294" alt="Screen Shot 2020-02-19 at 10 21 55 AM copy" src="https://user-images.githubusercontent.com/7570704/74852459-36a45200-5302-11ea-8349-1f34ab75afb8.png">

**Comment by gunjanmimo** [comment]
@leecalcote sir do i need any animation in the button?

**Comment by leecalcote** [comment]
@gunjanmimo, yes, you can reuse style from the Subscribe button.

**Comment by gunjanmimo** [comment]
@leecalcote sir I have added the animation
