### ISSUE TITLE
Incorporate display of " xxx performance tests run!"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#127]
**Current Behavior**
Meshery users send performance test results to the Meshery Cloud provider, but the total number of results collected isn't displayed on the site.

**Desired Behavior**
Similar to how https://layer5.io/meshery uses a public endpoint to display how many performance tests have been run, let's find a spot on meshery.io to display and explain this statistic.

<img width="655" alt="Screen Shot 2020-03-18 at 2 55 56 PM" src="https://user-images.githubusercontent.com/7570704/77001840-97867080-6928-11ea-98fc-8aa2d20b25a8.png">

**Comment by gunjanmimo** [comment]
![Screenshot from 2020-03-24 01-34-17](https://user-images.githubusercontent.com/46948185/77358307-9eb9de00-6d6f-11ea-8c4b-ffc7f07d5ad7.png)


@leecalcote sir, is this right place to show the performance test of Meshery?

**Comment by kanishkarj** [comment]
@gunjanmimo @leecalcote , I think that fits in perfectly with the rest of the UI! I Think, we could go ahead with this.

**Comment by leecalcote** [comment]
I agree with @kanishkarj. Double check, if you would, @gunjanmimo, is there space that we might eliminate between the current number and the rest of the "performance tests run!" sentence?
