### ISSUE TITLE
[Getting Started] Show only one set of instructions at-a-time

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#139]
**Description**
Getting Started section: Users are shown installation instructions for multiple platforms at the same time. 

**Expected Behavior**
Display of platform instructions should be dichotomous. 

**Screenshots**
<img width="1169" alt="Screen Shot 2020-03-30 at 9 29 46 PM" src="https://user-images.githubusercontent.com/7570704/77980841-0622e100-72ce-11ea-9626-70e7491736bd.png">

**Comment by leecalcote** [comment]
Reopening this issue as this behavior is still present. @dhruv0000, would you like to have a look?

**Comment by crustyy** [comment]
@leecalcote i think the issue has been resolved?

**Comment by Nikhil-Ladha** [comment]
> @leecalcote i think the issue has been resolved?

Yes, @crustyy . It has been!
