### ISSUE TITLE
[Getting Started] Do not allow nav menu bar to cut off section heading

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#141]
**Description**
A brief description of the issue.

**Expected Behavior**
Use the css class "anchor" to offset section headings from the nav bar. 

Example:
```<div class="anchor"><a name="getting-started"></a><h2>Run Meshery</h2></div>```

**Screenshots**
<img width="1169" alt="Screen Shot 2020-03-30 at 9 29 46 PM" src="https://user-images.githubusercontent.com/7570704/77981287-20a98a00-72cf-11ea-9ef0-18dd6553ebb2.png">

**Comment by vineethvanga18** [comment]
@leecalcote can i work on this

**Comment by leecalcote** [comment]
@vineethvanga18 that would be fantastic. Please do. 

As you go to investigate, please have a look at this [pull request](https://github.com/meshery/meshery.io/pull/156). If you're able to jump I there with an update that would be great. If it looks unwieldy, let's get you another issue to pick up on.

**Comment by vineethvanga18** [comment]
@leecalcote sure, thanks.I will look in to that

**Comment by leecalcote** [comment]
@vineethvanga18 if you haven’t joined the Meshery Slack community, yet, I welcome you to. It would be nice to have you - http://slack.meshery.io
