### ISSUE TITLE
[Getting Started] CSS overflow on widescreen

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery.io#144]
**Description**

CSS Overflow on getting started page.

**Expected Behavior**

Contents should be arranged to avoid the overflow.

**Screenshots**
<img width="1296" alt="Screenshot 2020-04-01 at 5 29 33 AM" src="https://user-images.githubusercontent.com/44091822/78085884-eed11a00-73d9-11ea-97d0-39e8e86fd39d.png">

**Comment by leecalcote** [comment]
Good eye!

Have a look-see at #138, #139, #140, #141, #142, if you would. Thank you for knocking out #143 already. 👍

**Comment by gunjanmimo** [comment]
@kushthedude is this problem happening in full screen/ normal screen?
I think this problem is arriving only for the mobile screen or tablet screen?
