### ISSUE TITLE
[Getting Started] Alignment issues in getting-started page

### ISSUE THREAD

**Issue by sachincool** [layer5io/meshery.io#155]
**Description**
There's some alignment issues in [here](https://meshery.io/#getting-started)

**Expected Behavior**
* Add some proper spacing between letter and numbers
* push the logos slightly right 

**Screenshots**
![image](https://user-images.githubusercontent.com/25671488/78396981-fa0c8b80-760d-11ea-81e2-6f49c7296ff9.png)

**Comment by leecalcote** [comment]
Good eye! There are few of these itemized here - https://github.com/meshery/meshery.io/issues. Please jump in, if you want to try your hand at correcting them. 👍

**Comment by leecalcote** [comment]
@sachincool no sweat. Issue has been transferred.
