### ISSUE TITLE
[Getting Started] Resposivness issue

### ISSUE THREAD

**Issue by Yashank18** [layer5io/meshery.io#161]
**Description**
The website isn't responsive when evaluated in a mobile or tab view.

**Expected Behavior**
The navbar should behave with white color and should align-items accordingly and Get Started Section data overflow and that creates a horizontal scroll.  

**Screenshots**
![Screenshot (132)](https://user-images.githubusercontent.com/46098062/80077310-f31ccd00-856a-11ea-86b2-0b55f4bbb15e.png)

**Enviroment:**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 81.0.4044.113 (Official Build) (64-bit)
 - Device: Acer Laptop

 **Additional Context**
What I can evaluate is due to Get Started Section the whole page is getting affected. There is a need for a better breakpoint for the navbar as well. If we add a better breakpoint for the Get started section, most of the opened issues will be resolved.

**Comment by leecalcote** [comment]
@Yashank18 awesome. Thanks for documenting this issue and being willing to jump in. 👍 

There are a number of related issues (#138 through #155) that you'll want to familiarize with as you look into this bug. It's fantastic to have you here!

**Comment by leecalcote** [comment]
@Yashank18 what do you think?

**Comment by Yashank18** [comment]
Hey, @leecalcote I am on it. I was busy with my exams but will update you for the same as soon as possible,

**Comment by leecalcote** [comment]
Sounds good, @Yashank18. Best of luck on your exams!
