### ISSUE TITLE
Add CI WG Meeting Event, Meeting Minutes links

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#162]
**Current Behavior**
The new [WG CI working group](https://docs.google.com/document/u/1/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit#heading=h.pjvwhi5pvz7) has been created. 

**Desired Behavior**
CI WG information needs added to the existing [connect.html](https://github.com/layer5io/meshery.io/blob/master/_includes/partials/connect.html)

**Comment by leecalcote** [comment]
@Vineet-Sharma29 would you like to wrangle this one?

**Comment by Vineet-Sharma29** [comment]
Sure!

**Comment by Vineet-Sharma29** [comment]
Should I add the details in `connect.html` or `community.html`? I think according to code given in index.html it should be in `community.html`
