### ISSUE TITLE
Addition of community calendar on website 

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery.io#164]
I propose to add the community calendar of Meshery Team Meetings on our website.

Soon we will be having more WG meetings in a week & having a calendar on our website will get our new & existing contributors more acquainted with same.

Something like this should be great https://kubernetes-contributor.netlify.app/events/community-calendar/ .

----
Note :- 
The upstream kubernetes calendar is not working due to error in keys .

**Comment by leecalcote** [comment]
This may help - ```<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FChicago&amp;src=bGF5ZXI1LmlvX2VoMmFhOWRwZjFnNDBlbHZvYzc2MmpucGhzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&amp;color=%23616161&amp;showTitle=1&amp;showNav=1&amp;showDate=1&amp;showPrint=1&amp;showCalendars=0" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>```

**Comment by kushthedude** [comment]
> This may help -
> 
> ```
> <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FChicago&amp;src=bGF5ZXI1LmlvX2VoMmFhOWRwZjFnNDBlbHZvYzc2MmpucGhzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&amp;color=%23616161&amp;showTitle=1&amp;showNav=1&amp;showDate=1&amp;showPrint=1&amp;showCalendars=0" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
> ```

I think that's your personal calendar 😅. Also how about using [fullcalendar](https://fullcalendar.io) rather than googles' naive one. It seems very ugly 
<img width="803" alt="Screenshot 2020-04-25 at 11 52 48 PM" src="https://user-images.githubusercontent.com/44091822/80287527-e73e3000-874f-11ea-9769-0c3b05dd875b.png">

**Comment by leecalcote** [comment]
Agreed - that is ugly. No, this is the Layer5 Community Calendar (same as linked in the "Connect" menu). My personal calendar is... well, unwieldy. :) Here's a screenshot of the embed code above as viewed in my desktop browser:

<img width="866" alt="Screen Shot 2020-04-25 at 1 24 32 PM" src="https://user-images.githubusercontent.com/7570704/80287688-59832600-86f8-11ea-9ebe-60bbe9e96758.png">

Yes, fullcalendar looks great to me. 👍

**Comment by leecalcote** [comment]
Hopefully, the publicly published settings of the current community calendar are all that is needed to integrate with fullcalendar. Let me know if not and we need to configure additional permissions.

**Comment by kushthedude** [comment]
> Hopefully, the publicly published settings of the current community calendar are all that is needed to integrate with fullcalendar. Let me know if not and we need to configure additional permissions.

I will be needing a key for the calendar, but since we are having a G-Suite it would be easy to manipulate the permissions of the key which we are exposing.

**Comment by leecalcote** [comment]
@Vineet-Sharma29 this enhancement is related some of our recent discussions...

**Comment by Vineet-Sharma29** [comment]
Would work on it

**Comment by leecalcote** [comment]
Thank you, @Vineet-Sharma29

**Comment by leecalcote** [comment]
@vineethvanga18 Do you want to try your hand at this one?

**Comment by vineethvanga18** [comment]
@leecalcote sure, I will work on it

**Comment by PluckyPrecious** [comment]
Hi @vineethvanga18  what's the situation report please? 😃

**Comment by chandrashritii** [comment]
@tripathyprateek Do signal if you want to work on this issue

**Comment by tripathyprateek** [comment]
Hey @chandrashritii I would take this issue up after I complete the other 2 tasks assigned to me. I faced some issues with Jekyll today which I will get fixed, and I will take this up after that.

**Comment by Nikhil-Ladha** [comment]
> Hey @chandrashritii I would take this issue up after I complete the other 2 tasks assigned to me. I faced some issues with Jekyll today which I will get fixed, and I will take this up after that.

In case you are still stuck with it, and are not able to come up with a solution. Feel free to ping me in slack :slightly_smiling_face:

**Comment by Nikhil-Ladha** [comment]
@Neilblaze ^^

**Comment by Neilblaze** [comment]
@Nikhil-Ladha the link which Kush provided redirects to a 404 page :confused:

**Comment by Nikhil-Ladha** [comment]
Yeah...I know maybe @leecalcote or @kushthedude can give some more insights here, on what's to be done.

**Comment by leecalcote** [comment]
Either of these two should work:

```
<iframe src="https://calendar.google.com/calendar/embed?src=layer5.io_eh2aa9dpf1g40elvoc762jnphs%40group.calendar.google.com&ctz=America%2FChicago" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```
and 

https://calendar.google.com/calendar/embed?src=layer5.io_eh2aa9dpf1g40elvoc762jnphs%40group.calendar.google.com&ctz=America%2FChicago
