### ISSUE TITLE
Empty author contents on SMI blog

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery.io#165]
**Current State:**

Empty author contents on SMI blog

**Desired State:**

Remove the weird empty block or add author details.

**Screenshot**

<img width="1080" alt="Screenshot 2020-04-25 at 11 46 42 PM" src="https://user-images.githubusercontent.com/44091822/80287405-12744f80-874f-11ea-90e8-84b773224f77.png">

---
**Contributor Resources**
- [Blog to be changed](https://meshery.io/blog/a-standard-interface-for-service-meshes)

**Comment by Akanksha1212** [comment]
Hi @kushthedude Can I work on this issue?

**Comment by kushthedude** [comment]
Hello @Akanksha1212, Please go ahead!

**Comment by Akanksha1212** [comment]
Thanks @kushthedude. From where can I find the author details?

**Comment by kushthedude** [comment]
> Thanks @kushthedude. From where can I find the author details?

Hi @Akanksha1212 , the following blog is written by Lee Calcote(@leecalcote) . Also, I invite you to join our [Slack](http://slack.meshery.io) to engage with the Meshery sevice mesh community & our core project [Meshery](https://meshery.io)

**Comment by leecalcote** [comment]
@Akanksha1212, are you thinking of working on this? That is exciting. That would be great. Ping your MeshMate or anyone of us if a chat here would be helpful.

**Comment by leecalcote** [comment]
Oh! I see now that you _are_ assigned to the issue. Perfect. 👍

**Comment by crustyy** [comment]
Heyy!! as the issue is still open is there something more to change?

**Comment by leecalcote** [comment]
@crustyy thanks for asking. PR https://github.com/meshery/meshery.io/pull/223 was not merged, but closed, so yes, this is still an open issue that needs worked on. I think @Akanksha1212 may circle around for another crack at this, but collaboration here would be most helpful. Perhaps, you'd like to take a shot at this and ask for @Akanksha1212 to review? If you run into questions, along the way, you might engage with her to "partner program".

Here's a great reference to give you a leg up - https://github.com/meshery/meshery.io/pull/223#pullrequestreview-434088656

**Comment by soumy47** [comment]
Hey, sir is it still an open issue ??@leecalcote

**Comment by ashiscs** [comment]
Yes @soumy47

**Comment by kushthedude** [comment]
Hi @soumy47 , There is a PR already opened by @crustyy you can find more open issues in the repository.

**Comment by soumy47** [comment]
alright @kushthedude

**Comment by kushthedude** [comment]
@soumy47 You can join our [slack](slack.meshery.io) to get acquainted with service meshes & work with Meshery, the service-mesh company.
