### ISSUE TITLE
Upgrade Jekyll site to Ruby 2.7.0

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#170]
**Current Behavior**
This site runs on Ruby 2.6.5.

**Desired Behavior**
Ruby 2.7.0 is available as a stable release. Ideally, this Jekyll site and the other Jekyll-based project sites are upgraded to use 2.7.0.

**Related Issues**
- meshery.io: https://github.com/layer5io/layer5/issues/393
- meshery docs: https://github.com/layer5io/meshery/issues/929

**Comment by leecalcote** [comment]
@rubenlorenzo conceptually, a simple update here. Would you like to take this one?

**Comment by rubenlorenzo** [comment]
@leecalcote I can programming HTML, CSS, Javascript, but Jekyll I know a little above.

**Comment by leecalcote** [comment]
If you like, this is a great place to learn. This upgrade will be straight-forward:

1. bump from 2.6.5 to 2.7.0 in the Gemfile
1. run `make site` locally to verify the site builds.

@ashiscs @gunjanmimo (both in Slack) can assist with any questions. No pressure (there is a long list of many other web programming issues to tackle here).

**Comment by gunjanmimo** [comment]
@leecalcote sir sure. @rubenlorenzo you can ping me on slack anytime

**Comment by ashiscs** [comment]
@rubenlorenzo ready to help you out !!

**Comment by ashiscs** [comment]
> @ashiscs @gunjanmimo, thanks. I go to look resolve. I ask you anything.

No issues @rubenlorenzo

**Comment by rubenlorenzo** [comment]
Hi @ashiscs @gunjanmimo, Already, I been able to manage versions of Ruby, in my system. I will look to do update Ruby in Jekyll. Could you assign the issues?

**Comment by leecalcote** [comment]
Thank you, @rubenlorenzo. 😄 

FYI, now that you're part of the Meshery community, you should find that you have the ability to triage issues (including self-assigning). 👍

**Comment by rubenlorenzo** [comment]
Ah ok, Thank you. @leecalcote

**Comment by ashiscs** [comment]
Yes @rubenlorenzo feel free to take up any issue (if it is already not assigned!)

**Comment by rubenlorenzo** [comment]
@ashiscs, Do I have to target the master branch of Jekyll? as described here as https://github.com/jekyll/jekyll/pull/7948#issuecomment-584132037 for the before message https://github.com/jekyll/jekyll/pull/7948#issuecomment-584127762. Also, would I have to update the Makefile inline 10 to master instead of 4.0.0?

**Comment by leecalcote** [comment]
cc @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
I guess you just need to update the Gemfile which has the ruby version to 2.7.0. and then try it out locally if everything is fine. If not you can do a bundle install to check for other dependencies if needed by it. Isn't it @leecalcote ?

**Comment by rubenlorenzo** [comment]
@leecalcote, @ashiscs, and @Nikhil-Ladha I have managed to launch meshery.io with ruby 2.7.0. I had to correct incompatibilities with:
>  gem pristine --all

At present, it has come out jekyll4.0.1, but in docker hub [Jekyll](https://hub.docker.com/r/jekyll/jekyll/tags) has not yet arrived. Better, I wait for the new version to come out, right? I do the pull request.

**Comment by nik-redhat** [comment]
@rubenlorenzo I suppose this change does not need updating jekyll version. You just have to update the ruby version in the Gemfile to 2.7.0 and hit the `make site` command to test it out. And you will good to go. Same goes for other sites as well i.e, the Docs site and the meshery site.
