### ISSUE TITLE
Add Aayush Dutt as a community member

### ISSUE THREAD

**Issue by willcalcote** [layer5io/meshery.io#171]
****Current Behavior**
@aayushdutt is a new community contributor.

**Desired Behavior**
A profile for @aayushdutt should be created and visible on `/community`.**

**Comment by aayushdutt** [comment]
This is so cool! :smiley:

**Comment by aayushdutt** [comment]
I think something went wrong
https://meshery.io/contributors/aayush-dutt/
![image](https://user-images.githubusercontent.com/25280541/80779127-4e147c80-8b88-11ea-9626-0766dbfb1c5d.png)

**Comment by leecalcote** [comment]
Looks like some invalid yaml. A fixed has been pushed.

**Comment by ashiscs** [comment]
@aayushdutt here you go
https://meshery.io/contributors/aayush-dutt/
