### ISSUE TITLE
Publish Meshery Presentation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#172]
**Current Behavior**
The [Meshery - The Service Mesh Management Plane](https://drive.google.com/open?id=14kxjwYSJ_FyE3K_6CDEd6oq2kqwn0OSE8RDJ4H-KlKU) presentation gives an overview of the project and related projects. 

**Desired Behavior**
It would be good to have on the meshery.io site as a published Google Slide.

**Comment by leecalcote** [comment]
@Akanksha1212 you might want to try your hand at this one...

**Comment by Akanksha1212** [comment]
Sure.Will give it a try.

**Comment by Akanksha1212** [comment]
@leecalcote Where on meshery.io should the presentation be published? Like just before the 'getting started with meshery' section on homepage or any other location?

**Comment by Nikhil-Ladha** [comment]
Hi @Akanksha1212 , I guess publishing it on the olace you suggested is exactly correct, just above the Getting Started section would be a wise choice.

**Comment by morrme** [comment]
Would this resolve #193 or is there a larger goal of a dedicated section?

**Comment by leecalcote** [comment]
@morrme you're right that we have other talks and presentations about Meshery to share. We capture these on layer5.io/meshery and docs.meshery.io today, but may want to consider capturing them on meshery.io, too.

**Comment by leecalcote** [comment]
@NupurThakur27 gave a recent presentation that might make sense to add to the list.

**Comment by chandrashritii** [comment]
@morrme There definitely are other presentations and talks that deserve to be in the list. This would probably need to be updated in the existing docs as well as in the future section on meshery.io (#193). Let me know if you need any help in looking for the presentations, adjusting layouts or anything else :)

**Comment by morrme** [comment]
@chandrashritii Thanks but I am not actually involved with the other issue.  I just noticed these two were similar and wondered if resolving one would resolve the other.  I believe @gunjanmimo  is working on 193.

**Comment by leecalcote** [comment]
@gunjanmimo shifted his focus away from this community for the time being. Any issues assigned to him may be reassigned.

**Comment by chandrashritii** [comment]
@morrme As @leecalcote explained, @gunjanmimo isn't actively working on it anymore and the issue hasn't been reassigned yet. If you're up to doing it, it is yours for the taking ;)

**Comment by morrme** [comment]
@chandrashritii I'm not involved with that issue, I just mentioned it as I was reading through issues. Feel free to assign to someone else :)
