### ISSUE TITLE
[Getting Started] Breaking of screen width on opening navigation menu in mobile view

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/meshery.io#177]
**Description**
In mobile view, on clicking the menu button the page expands to it right showing blank space.

**Expected Behavior**
The page should not expand and the menu items should be listed properly.

**Screenshots**
![Screenshot_20200501-102507__01](https://user-images.githubusercontent.com/29438875/80783326-0a753f00-8b97-11ea-9d2f-9f88a47317c8.jpg)

**Comment by leecalcote** [comment]
@rubenlorenzo thank you for taking a look into these issues. The are prominent bugs for anyone first coming to the project!

**Comment by rubenlorenzo** [comment]
Hi @leecalcote, I shouldn't have assigned it to myself? at present, I am with another issue #155. In this, I will have to configure my mobile to develop. This error only appears on the mobile, exactly.

**Comment by Nikhil-Ladha** [comment]
Hey @rubenlorenzo , no worries if you are equipped with some other work. You can work on it with time, but if it's really not possible for you then you can unassign yourself.
And as far as working on it is concerned, you don't need to configure any mobile device in my experience 😅. You can just adjust the display in the browser developer tools itself 🙂.

**Comment by rubenlorenzo** [comment]
@Nikhil-Ladha In the browser in mobile simulation no appear exactly the same for mine. At the moment I leave it for another. Later I will look at it again if it is not assigned.

**Comment by Nikhil-Ladha** [comment]
We are good to close this issue 🙂.
