### ISSUE TITLE
Create contributor profile for Ruben Lorenzo

### ISSUE THREAD

**Issue by willcalcote** [layer5io/meshery.io#183]
**Current Behavior**
@rubenlorenzo is a new community contributor.

**Desired Behavior**
A profile for @rubenlorenzo should be created and visible on `/community`.

**Comment by leecalcote** [comment]
@rubenlorenzo, thanks for your good work on upgrading the Jekyll sites. Let's get you into another area of the projects. We've really struggled to get someone to fix all the issues with the Getting Started section of the meshery.io site - https://meshery.io/#getting-started. Would you like to take a crack? See the issues with [Getting Started] in their title.

**Comment by rubenlorenzo** [comment]
Thanks, @leecalcote. I look which them, I can resolve.
