### ISSUE TITLE
[CI] Netlify error: Your Ruby version is 2.7.0, but your Gemfile specified 2.6.5

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#198]
**Description**
Netlify builds fail with
‘’’

7:58:53 PM: Your Ruby version is 2.7.0, but your Gemfile specified 2.6.5
‘’’

**Comment by Nikhil-Ladha** [comment]
Can this be related to the recent update on the Gemfile for the ruby version? 🤔

**Comment by kushthedude** [comment]
The error should only be present in the PR which are a month old when we had not updated our gemfile. Like in #156, since the branch is not updated with the master there is this error.

**Comment by leecalcote** [comment]
Ok, sounds like this issue can be closed in that case.
