### ISSUE TITLE
Ability to tag and filter the view of community members.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#209]
**Desired Behavior**
It would be nice if we were able to filter the view of community members by those that carry different roles / badges (e.g. see all MeshMates).

**Comment by NupurThakur27** [comment]
@ishita-kumar Do you think this could be a good start for you?

**Comment by ishita-kumar** [comment]
@NupurThakur27  This seems great! Perhaps if I could get some more information on what exact functionality needs to be added it would help?

**Comment by hinupurthakur** [comment]
@ishita-kumar If you would have seen the Community page of Meshery.io then on clicking the picture of any community member you will see a Designation mentioned below their image and name. So I think if those tags can help filter the community into groups.
@leecalcote Sir do you think you could explain the functionalities with more clarity?

**Comment by leecalcote** [comment]
Using the front matter of each markdown file in the [_contributors collection](https://github.com/meshery/meshery.io/tree/master/collections/_contributors), create either a new page (/community/meshmates) or the ability to filter on the existing page contributor profiles that include `MeshMate` in their role. Jekyll loop and conditionals can be used to iterate over a collection.

**Comment by morrme** [comment]
@ishita-kumar  If you want an example of how loops/conditionals work in Jekyll, take a look at the [Adapters page](https://github.com/meshery/meshery/blob/master/docs/pages/service-meshes/adapters.md)
cc: @leecalcote @NupurThakur27

**Comment by crustyy** [comment]
@leecalcote can i take this issue as there is no one assigned!

**Comment by Shokescodes** [comment]
@leecalcote Haven't quite gotten the hang of it. I couldn't locate the community-member.md folder in the code base

**Comment by Nikhil-Ladha** [comment]
> @leecalcote Haven't quite gotten the hang of it. I couldn't locate the community-member.md folder in the code base. Please help.

Here it is @Shokescodes 🙂https://github.com/meshery/meshery.io/tree/master/collections/_contributors

**Comment by Shokescodes** [comment]
Hi @Nikhil-Ladha . I successfully located the folder. Who are the new members I'm supposed to add?

**Comment by Nikhil-Ladha** [comment]
@Shokescodes you don't need to add anyone, you will have to add a feature to filter the members in the in the community based on the role they or position they have.

**Comment by Nikhil-Ladha** [comment]
@crustyy are you working or started to work on this issue?

**Comment by crustyy** [comment]
yes @Nikhil-Ladha but now i can see someone else is already working that's why i will back off:)

**Comment by Nikhil-Ladha** [comment]
Ohh. Nice of you @crustyy 🙂

**Comment by Nikhil-Ladha** [comment]
Thn, @Shokescodes it's an open field for you to play around. Go ahead make something meshy, but in the way if you are stuck anywhere feel free to ping me in slack😎.

**Comment by leecalcote** [comment]
Related - https://github.com/meshery/meshery/issues/739

**Comment by kishore007k** [comment]
I would like to work on this issue If it is still open.

**Comment by Nikhil-Ladha** [comment]
> I would like to work on this issue If it is still open.

Yes please @kishore007k 💯
