### ISSUE TITLE
[Docs] Add description of MeshMates program.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#228]
**Current State:**
MeshMates is our newcomer onboarding program. It is described in brief here - https://layer5.io/community and in full here - https://docs.google.com/document/d/1vquQMD0TTWREahpx_JXuvIbQ4hM2_4jrVFk8xqZ72ok/edit

**Desired State:**
This program should be included in:

- [ ]  the Community page.

**Comment by kushthedude** [comment]
@itsapoorvj Would you like to knock this out ?

**Comment by itsapoorvj** [comment]
Sure!!

**Comment by itsapoorvj** [comment]
@kushthedude , Its already added in community page: https://meshery.io/community

**Comment by ashiscs** [comment]
@itsapoorvj, it needs to be added here https://meshery.io/community/

**Comment by kushthedude** [comment]
The community page of meshery is already occupied by the contributors, adding the program details on it will make the page ugly. @leecalcote How about adding a new page for the mentoring initiatives & the programs in which Meshery has participated?

**Comment by ashiscs** [comment]
> The community page of meshery is already occupied by the contributors, adding the program details on it will make the page ugly. @leecalcote How about adding a new page for the mentoring initiatives & the programs in which Meshery has participated?

Agree !

**Comment by leecalcote** [comment]
Gents, good suggestion. Sounds real good.

**Comment by Ruth-ikegah** [comment]
@ashiscs has the page been created?

**Comment by ashiscs** [comment]
> @ashiscs has the page been created?

No, i guess @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
> > @ashiscs has the page been created?
> 
> No, i guess @Ruth-ikegah

I can find it on meshery.io site but not on meshery.io

**Comment by leecalcote** [comment]
@Ruth-ikegah given the description of the MeshMates program on the meshery.io site, instead of capturing a description of the program directly on meshery.io, let's link to the description on meshery.io/community/meshmates. This link can be included on any member profile that has the MeshMate title.

@Ruth-ikegah here is an issue that we really would like to see implemented - https://github.com/meshery/meshery.io/issues/209.

**Comment by Ruth-ikegah** [comment]
> @Ruth-ikegah given the description of the MeshMates program on the meshery.io site, instead of capturing a description of the program directly on meshery.io, let's link to the description on meshery.io/community/meshmates. This link can be included on any member profile that has the MeshMate title.
> 
> @Ruth-ikegah here is an issue that we really would like to see implemented - #209.

Cool, I'd check out the issue.

**Comment by leecalcote** [comment]
transitioning the majority of the community member profiles and the MeshMate program description to meshery.io/community
