### ISSUE TITLE
Change meshery.io site font to Open Sans

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#233]

**Comment by vineethvanga18** [comment]
@leecalcote I changed the body to this in elements.scss
will this do?
body {
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
Before:
![Screenshot from 2020-06-26 21-43-53](https://user-images.githubusercontent.com/44473939/85878428-4d017380-b7f6-11ea-97e6-dceb78c4682d.png)

After:
![Screenshot from 2020-06-26 21-40-29](https://user-images.githubusercontent.com/44473939/85878185-f2681780-b7f5-11ea-9c3f-14a92cc08f3f.png)

**Comment by leecalcote** [comment]
@vineethvanga18 Yes, nice! I'll have another look when the PR is up, but this looks good to me. 👍

**Comment by leecalcote** [comment]
@vineethvanga18 would you like take another attempt at this one?

**Comment by vineethvanga18** [comment]
@leecalcote any changes required wrt previous PR?

**Comment by leecalcote** [comment]
Here's a screenshot of what I see on meshery.io currently:

<img width="1189" alt="Screen Shot 2020-06-29 at 11 19 57 PM" src="https://user-images.githubusercontent.com/7570704/86083148-167a6180-ba5f-11ea-80a2-d7186be25e77.png">

Open Sans isn't shown. It may be the case that this font needs to be explicitly loaded (linked to) like so: `<link rel="stylesheet"  href="https://fonts.googleapis.com/css?family=Open Sans">`

**Comment by vineethvanga18** [comment]
@leecalcote It's working fine on my browser,dont know why.But if u want me to send a PR after including "<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">" ,I will send it right away.

**Comment by vineethvanga18** [comment]
@leecalcote It's working fine on my browser,don't know why.But if u want me to send a PR after linking the font, I will send it right away.

**Comment by leecalcote** [comment]
@vineethvanga18 Yes, if you would. I'm not sure that linking the font is the only change that will be needed. You may have to list the Open Sans font family first and/or may other?

**Comment by leecalcote** [comment]
@vineethvanga18 thanks for this work. FYI, if you include a keyword like "fixes" and then the issue number (#233) in the PR description, GH will auto-close the related issue.
