### ISSUE TITLE
Remove scrollbars

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#238]
@Nikhil-Ladha here's an item (the scrollbars) that you might take a look at: 

<img width="715" alt="Screen Shot 2020-06-28 at 8 30 19 AM" src="https://user-images.githubusercontent.com/7570704/86052364-7e5b8880-ba1c-11ea-9de1-1a63600d36b1.png">

_Originally posted by @leecalcote in https://github.com/layer5io/meshery.io/pull/237#issuecomment-651340896_

**Comment by Nikhil-Ladha** [comment]
Yes, @leecalcote I saw this. But the thing is that this scrollbar is coming only in the browser for netlify preview and it wont come up when it's actually deployed. I tried it out for small screens in my mobile and pc and there a more friendly transparent scrollbar comes up which doesn't has any effect.
But if still, this needs to be removed I can do this by changing the code to `pre-formatted` style.

**Comment by leecalcote** [comment]
@Nikhil-Ladha, oh, interesting. Yes, I only looked at the netlify preview. Thank you for double-checking on this.

**Comment by leecalcote** [comment]
I checked on meshery.io and I do not see this behavior on the site. Closing issue.

**Comment by Nikhil-Ladha** [comment]
Cool 👍🏼🙂
