### ISSUE TITLE
Community section needs updated to reflect many weekly meetings

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#245]
**Current Behavior**
There are many different meetings held each week. The current community section doesn't list them all. 

**Desired Behavior**
Instead of saying “Join weekly community meeting on Fridays from 10am - 11am Central.“, it should say “Join community meetings on the community calendar.”

---
[Optional] **Alternatives**
Add the community calendar as described here - https://github.com/layer5io/meshery.io/issues/164

**Comment by morrme** [comment]
The second line says : "Watch community meeting recordings and subscribe to the community calendar." 
Would you still want that line, or would you want the "and subscribe to..." part removed in favor of the line above?

**Comment by leecalcote** [comment]
@morrme great question. My example phrasing in the issue description is grammatically incorrect. 

My feeling is that asking people to subscribe may force them to decide whether to make a commitment or not (a word that if can avoid, it would be nice to - - not critical, though).

Here is a better phrasing example - https://github.com/meshery/meshery#join-the-service-mesh-community:

<img width="835" alt="Screen Shot 2020-07-02 at 3 10 31 PM" src="https://user-images.githubusercontent.com/7570704/86404988-30da5800-bc76-11ea-8e61-3da336fa8c73.png">

Thank you for jumping in here, @morrme! 👍

**Comment by leecalcote** [comment]
> The second line says : "Watch community meeting recordings and subscribe to the community calendar."
> Would you still want that line, or would you want the "and subscribe to..." part removed in favor of the line above?

Oh, wait. I misread your question and actually missed the fact that this sentence is already present.

Yes, if you would please displace both of the first bullet points with a consolidated statement akin to that of the one using in the screenshot above.

**Comment by leecalcote** [comment]
@morrme also, I welcome you to join the community, too. It would be fantastic to have you jump into the Meshery Slack - http://slack.meshery.io. 😄

**Comment by morrme** [comment]
@leecalcote Thank you for the warm welcome!
