### ISSUE TITLE
Upgrade to Jekyll 4.0.1

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#252]
**Current State:**
The meshery.io site is running Jekyll 4.0.0.

**Desired State:**
The meshery.io site needs to be updated to Jekyll 4.0.1.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@morrme how is your comfort level here?

**Comment by morrme** [comment]
@leecalcote I am not very experienced with this process, so I'd need to go over the steps again....

**Comment by kushthedude** [comment]
@crustyy Do you think you can take it? It is a straightforward change, what do you say ?

**Comment by crustyy** [comment]
Yes I'll take it

**Comment by morrme** [comment]
@kushthedude sorry I wasn't fast enough on this one! good luck with it!

**Comment by kushthedude** [comment]
Fixed in #262
