### ISSUE TITLE
Update Quick Start instructions

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#256]
**Description**
The second quick start instruction is wrong: "Access Meshery in your browser if you are using Kubernetes at http://127.0.0.1:9081."

**Expected Behavior**
The instruction should be "Open Meshery in your browser."

**Comment by morrme** [comment]
@leecalcote Is this the culprit? https://github.com/meshery/meshery.io/blob/13c032b47e45b867ead64f06526a1f3d5025111b/_includes/getting-started.html#L178

**Comment by leecalcote** [comment]
Right on, @morrme. ✔️
