### ISSUE TITLE
All images should have hyperlink to full-sized image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#26]
**Current Behavior**
The screenshots / images in the site are not clickable. Some screenshots are better viewed at a larger size.

**Desired Behavior**
All thumbnail images should be hyperlinked to their original full-size image.

**Comment by leecalcote** [comment]
@subhamkrai please have a look at #44.

**Comment by subhamkrai** [comment]
@leecalcote  I was going through issues and #44 and it was closed by @ashiscs.

**Comment by ashiscs** [comment]
Bhaiya (@subhamkrai ) I fixed this issue properly, so it was closed on merging.
