### ISSUE TITLE
[Community] Some of the community member profile pictures need to be squared (in aspect ratio)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#274]
**Description**
A number of the community member profile pictures are skewed by the constraints put on the picture as displayed with a circle affect on https://meshery.io/community.

**Expected Behavior**
The aspect ratio of each of the community member photos should be square, so as to avoid being skewed in shape.

**Implementation**
- In some cases, pictures can be cropped / adjusted to be square in shape.
- In other cases, a new picture may need to be requested from the member.

**Comment by vineethvanga18** [comment]
@leecalcote I will take up this issue

**Comment by leecalcote** [comment]
Thank you, @vineethvanga18. That would be great.

**Comment by vineethvanga18** [comment]
@leecalcote put constraints of 300x300 and used (object-fit: cover), so that aspect-ratio is preserved
![Screenshot from 2020-07-24 02-23-08](https://user-images.githubusercontent.com/44473939/88337730-d1dba080-cd54-11ea-8864-6e73ade95768.png)

**Comment by leecalcote** [comment]
@vineethvanga18 Nice! If you're able to keep the border-radius, yes, effect is desired.
