### ISSUE TITLE
Create Active vs Inactive Member View

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#276]
**Current Behavior**
We've had many fantastic contributors to the Layer5 projects including the Meshery project. One of the ways that we attempt to recognize a community member's _consistent_ contribution is by providing them with a profile on any one or more of the Layer5 project websites. As a community grows, it becomes more difficult to elevate the works and profiles of those giving of their time and positively impacting projects. 

We strive to represent and recognize these individuals. As such, Layer5 projects will use  "active" and "inactive" designations to identify the status of a community member. An organic side effect of actively contributing is the inevitability of becoming an inactive contributor. Any given member's contributions and activities within the community, naturally ebb and flow based on other competing priorities in their personal and professional lives. Once a community member has contributed, their contributions stand for all time. 

Active and inactive designation as will be manually determined. A given member's status manually updated based on periodic reviews. The manual nature of this determination and status update is primarily be due to the fact that what defines a "contribution" is much more than code (there is a long list of activities that individuals perform that assist in advancing projects) and those contributions can be measured in a variety of ways. A member that goes inactive may return at any point, resume contributing and have their profile return to "active". Members are always warmly welcomed back.

**Desired Behavior**
The meshery.io/community page should provide a filter to view "active" members, "inactive" members, and all members. Additionally, this filter will ideally interface with a similar filter to view community members that carry different roles / badges (e.g. a view to show all MeshMates).

**Implementation**
- Add a `status` attribute in the front matter of each [community member's data file](https://github.com/layer5io/meshery.io/tree/master/collections/_contributors).
- Assign a value of "active" to all members (for now).
- Use CSS-only to allow the toggling of the visibility of members by active, inactive, and all.
- Avoid using Javascript, if possible.
- Avoid a multi-page implementation, if possible. (e.g. avoid -  `/community/members/active`, /community/members/inactive`)
- By default, the page should only show "active" members.

---
 **Additional context**
- See PR #https://github.com/layer5io/meshery.io/pull/273 for reference.
- See https://github.com/layer5io/meshery.io/issues/209#issuecomment-651524691 for an implementation example

**Comment by Neilblaze** [comment]
Hey @leecalcote , can I propose a better implementation idea upon this?

For the implementation part, the first two bullets are crystal clear for me. But how about if we add "Green Circular borders" around contributor images, which will mark the active status of that respective contributor, & is controlled via CSS toggling(yes it will be manual, which may be implemented later), but this approach seems much more surgical to me :)

And the best part is that, we can easily avoid using Javascript as well as a multi-page implementation as you have mentioned above.

By default, the page should only show "active" members. The implementation will somehow look like this - 

![c_prof](https://user-images.githubusercontent.com/48355572/89269239-4668e600-d657-11ea-9369-e7fe9e58aaf2.JPG)

**Comment by Nikhil-Ladha** [comment]
I think we can try this, also while filtering it would be better to have circle filled with green/red color in the left of active/inactive in the filter dropdown. How about that @Neilblaze ?

**Comment by Neilblaze** [comment]
Yes, I agree with you @Nikhil-Ladha . I guess then it'll look like this - 

![c_prof2](https://user-images.githubusercontent.com/48355572/89271051-d1e37680-d659-11ea-90a1-d2d24a75d4d9.JPG)

**Comment by Nikhil-Ladha** [comment]
Yeah, what say @leecalcote ?

**Comment by Neilblaze** [comment]
But @Nikhil-Ladha  I also think that red will look a bit aggressive, the better approach will be, either keep the green circular border for active community members else, leave it as it is. Views are my own :)

But if we do it as you mentioned, then we have to register two classes & link it with status attribute as @leecalcote mentioned.
Logic will be ~

if active => Green
if inactive => Red

**Comment by Nikhil-Ladha** [comment]
> But @Nikhil-Ladha I also think that red will look a bit aggressive, maybe we should either keep the green circular border for active community members else, leave it as it is. Views are my own :)
> 
> But if we do it as you mentioned, then we have to register two classes & link it with status attribute as @leecalcote mentioned.
> Logic will be ~
> 
> if active => Green
> if inactive => Red

Registering two classes is not an issue, but yes using red may seem a bit aggressive I support that. So, what we can do is that for the time being you go ahead with only adding the green color for active members. Later, on if we think adding red or something else for inactive makes more sense we will update it.

**Comment by Neilblaze** [comment]
Sure, I'm on it 😃

**Comment by leecalcote** [comment]
Light gray for inactive will do the trick and/or reducing the opacity of their profile picture.

See the color scheme for the appropriate green - meshery.io/brand

**Comment by Nikhil-Ladha** [comment]
I think reducing the opacity shall be a better call here.

**Comment by Neilblaze** [comment]
@leecalcote @Nikhil-Ladha I guess this will be good? - 

![trex](https://user-images.githubusercontent.com/48355572/89379300-344c7d80-d713-11ea-8d04-e6aabc4259fd.JPG)

Color scheme set to appropriate green(for active) & grey(for inactive) from [here](https://meshery.io/brand)

**Comment by Nikhil-Ladha** [comment]
Yes, go ahead with this.
