### ISSUE TITLE
Right-align mobile view's navigation menu (hamburger)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#288]
@leecalcote We need to fix a few things in mobile view

- hem burger icon in the navbar needs to be shifted towards the right

- footer needs to be center-aligned

<img width="325" alt="Screenshot 2020-08-09 at 3 45 20 PM" src="https://user-images.githubusercontent.com/43807816/89731721-ef07b300-da66-11ea-8184-c2fdc465c356.png">

- And "Overview" can be center-aligned  
![WhatsApp Image 2020-08-09 at 3 43 31 PM](https://user-images.githubusercontent.com/43807816/89731883-49554380-da68-11ea-8635-866b216f0c67.jpeg)

_Originally posted by @manishdangi98 in https://github.com/layer5io/meshery.io/pull/285#issuecomment-671045934_

**Comment by Code-Ebullient** [comment]
Ohh... i just notice this issue, was taking about it earlier
