### ISSUE TITLE
Center "Overview" heading for slide section when in mobile view

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#290]
See the following screenshot for an out of alignment heading.

- And "Overview" can be center-aligned  
![WhatsApp Image 2020-08-09 at 3 43 31 PM](https://user-images.githubusercontent.com/43807816/89731883-49554380-da68-11ea-8635-866b216f0c67.jpeg)

_Originally posted by @manishdangi98 in https://github.com/layer5io/meshery.io/pull/285#issuecomment-671045934_

**Comment by Code-Ebullient** [comment]
@leecalcote , i'll like to work on this... I noticed also that the hamburger menu is not properly aligned too on mobile size... i can do both on one issue right?
