### ISSUE TITLE
[Features] Bottom align "get started" links.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#292]
Also, we need to fix the margin of "get started"

![B1](https://user-images.githubusercontent.com/48355572/89727443-b48c1f00-da42-11ea-814c-a1b5d61f0f59.JPG)

To this - 

![B2](https://user-images.githubusercontent.com/48355572/89727477-fcab4180-da42-11ea-9a63-8dddf2eaa1e5.JPG)

@leecalcote

_Originally posted by @Neilblaze in https://github.com/layer5io/meshery.io/pull/284#issuecomment-671020022_

**Comment by Neilblaze** [comment]
Sure I'm on it :racing_car:

**Comment by Nikhil-Ladha** [comment]
@Neilblaze this has been resolved right? Please do confirm and take action on the issue accordingly.

**Comment by Neilblaze** [comment]
Yup! This issue got fixed with one of my merged PR's. But I don't know why, things got reverted back :confused:

**Comment by Nikhil-Ladha** [comment]
Can you please send out a quick PR for that?

**Comment by Neilblaze** [comment]
@Nikhil-Ladha umm can we keep it as an hacktoberfest issue :laughing: ?

**Comment by leecalcote** [comment]
Not to worry, we will have lots of hacktoberfest issues. 🤠

**Comment by leecalcote** [comment]
That'll teach to you mistreat your motherboard, @Neilblaze. tsk, tsk, tsk.  😜

**Comment by chinmaym07** [comment]
Hey @leecalcote Can I work on this.?

**Comment by Neilblaze** [comment]
@chinmaym07 go for it! :+1:
