### ISSUE TITLE
[Child] Add CNCF Landscape logo to meshery.io

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#297]
**Current Behavior**
Meshery has been accepted into the CNCF Landscape - https://layer5.io/news/meshery-accepted-into-cncf-landscape

**Desired Behavior**
This fact should be reflected on the meshery.io website alongside other programs that Meshery is participating in (e.g. GSoC, CommunityBridge and so on).

**Implementation**
- Select one of the SVGs here - https://github.com/cncf/artwork/tree/master/other/cncf-landscape - based on the most appropriate fit in context of other logos in the Participation section of the site.

**Comment by koladeafeez** [comment]
working on this

**Comment by koladeafeez** [comment]
@leecalcote , I created a PR for this issue, Waiting for it to be review
