### ISSUE TITLE
[Parent] Add Program Participation section on meshery.io

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#298]
**Current Behavior**
Meshery participation in a number of programs. 

**Desired Behavior**
A new section should be created to display the logos of these programs (e.g. GSoC, CommunityBridge and so on).

**Implementation**
- See related issues: #297

**Comment by UdokaVrede** [comment]
@leecalcote I would love to take this up but would definitely need a guide on this and further details

**Comment by leecalcote** [comment]
Hi @UdokaVrede, good deal. Here are the programs that Meshery participates in - https://layer5.io/programs. Logos for each of the programs can be found on the layer5.io site.  // @PluckyPrecious
