### ISSUE TITLE
Mention about SMI Conformance Tool in the website

### ISSUE THREAD

**Issue by kushthedude** [layer5io/meshery.io#315]
**Description**
SMI Tool is well integrated into Meshery Adapter for OSM & Istio, and will soon be available in others. Mention about SMI Conformance Tool of Meshery on the homepage of the website.

Take the Tool info & screenshot of the results from the Meshery Google Slide added on the meshery.io

---

**Comment by leecalcote** [comment]
@KarenEfereyan you might consider taking this on. This [deck](https://docs.google.com/presentation/d/14kxjwYSJ_FyE3K_6CDEd6oq2kqwn0OSE8RDJ4H-KlKU/edit#slide=id.g820d9370f8_0_0) (see on the meshery.io page) has a slide and screenshot that can be used here.

**Comment by KarenEfereyan** [comment]
Sure thing @leecalcote  assign it to me

**Comment by leecalcote** [comment]
Completed.
