### ISSUE TITLE
Adding Jubayer Joy as contributor 

### ISSUE THREAD

**Issue by willcalcote** [layer5io/meshery.io#316]
**Current Behavior**
@JubayerJoy a new community contributor.

**Desired Behavior**
A profile for @JubayerJoy should be created and visible on `/community`.

**Comment by JubayerJoy** [comment]
Thanks for this! 🤩

**Comment by leecalcote** [comment]
Whoo-hoo! 💯 

With our transition to member profiles to https://layer5.io/community/members, let's close this mid-flight issue and land Mr. Joy over there.
