### ISSUE TITLE
Add Reminder in the Welcome Bot to Star the Meshery.io Project 

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/meshery.io#319]
**Current Behavior**
 A welcome bot has been configured to usher in contributors new to this project. However, a reminder to star the project is missing in the message.

**Desired Behavior**
 The [config.yml](https://github.com/layer5io/meshery.io/blob/master/.github/config.yml) should be updated, you can take a cue from the highlighted [line 22](https://github.com/layer5io/meshery-consul/blob/master/.github/config.yml#L22)

**Comment by hikky08** [comment]
I would love to work on this
