### ISSUE TITLE
Add Community Calendar icon/link to Footer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#322]
**Current State of the Meshery.io site**
The current footer on meshery.io is missing a link to the Layer5 Community Calendar.

<img width="189" alt="Screen Shot 2020-08-30 at 9 39 38 PM" src="https://user-images.githubusercontent.com/7570704/91677842-97121880-eb09-11ea-952d-272e74e1bf60.png">

**Desired State of the Meshery.io site**
Akin to the community calendar icon/link in the https://layer5.io footer, the meshery.io footer should have a similar icon and link to the calendar.

<img width="373" alt="Screen Shot 2020-08-30 at 9 42 33 PM" src="https://user-images.githubusercontent.com/7570704/91677921-c759b700-eb09-11ea-9019-bbc164772cb8.png">

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by claire-me** [comment]
Hello @leecalcote I'd love to take this issue

**Comment by claire-me** [comment]
but i will need help locating the folder that contains "contacts" @leecalcote

**Comment by Nikhil-Ladha** [comment]
> but i will need help locating the folder that contains "contacts" @leecalcote

Here you go @claire-me https://github.com/meshery/meshery.io/blob/master/_includes/social-icon.html
This gile contains all the icon for the footer and the file footer.html in the same directory contains the code for the footer of the site.

**Comment by prasanjit15** [comment]
If this issue is not been worked upon, Can I take this up?

**Comment by claire-me** [comment]
Yes, you can. Been having issues setting up Jekyll

**Comment by tripathyprateek** [comment]
> Yes, you can. Been having issues setting up Jekyll

@claire-me take a look at [this](https://jekyllrb.com/docs/installation/windows/) . You dont need to complete Step 2 and 3 of ridk install. The projects works correctly without that as well. Just clone the repo, make sure you do all steps in the above link, then go to the repo in your local machine, `npm install` and `npm start`.

**Comment by tripathyprateek** [comment]
@prasanjit15 assigned you this task.

**Comment by PluckyPrecious** [comment]
> Yes, you can. Been having issues setting up Jekyll

Hi @claire-me what OS are you using? [This here](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#set-up-your-development-environment) would help. If issues persist please ping me on the community [slack](http://slack.meshery.io/)

**Comment by prasanjit15** [comment]
After addition of the icons below in contact. Is the social tab required further or can I remove it completely?

**Comment by prasanjit15** [comment]
Can anyone please provide me with the link that I have attach with the calendar icon

**Comment by Nikhil-Ladha** [comment]
> Can anyone please provide me with the link that I have attach with the calendar icon

Same as in the meshery site.

**Comment by prasanjit15** [comment]
Hii @leecalcote, 
I have fixed the issue by adding the community calendar and making the necessary changes. Kindly verify PR #[337 ](https://github.com/meshery/meshery.io/pull/337) and merge it.

**Comment by Nikhil-Ladha** [comment]
Closed #337

**Comment by leecalcote** [comment]
Thanks for this, @prasanjit15. 👍 

I don't know if this is captured elsewhere, but you know what else would be lovely, @prasanjit15? - - the same coloration onHover of these buttons like you can see in the current https://meshery.io site's footer.

**Comment by leecalcote** [comment]
Oops. I got my site's mixed up. I thought this PR was on the `meshery-ng` branch of the meshery/meshery repo.

The coloration onhover in the meshery.io footer is excellent. The Meshery-ng site could use the same interaction.

**Comment by prasanjit15** [comment]
Thanks a lot @leecalcote .
