### ISSUE TITLE
[Internship Programs] Replace old GSoC with CommunityBridge

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#328]
**Current State of the Meshery.io site**
Meshery participates in CommunityBridge - https://people.communitybridge.org/project/0d6fd362-04a1-4086-a6e7-ec753ed4a60b. CommunityBridge is missing from this list:

<img width="1379" alt="Screen Shot 2020-09-24 at 2 22 58 PM" src="https://user-images.githubusercontent.com/7570704/94192495-a5d3bd00-fe74-11ea-9055-831f51d56a5d.png">

**Desired State of the Meshery.io site**
1. add communitybridge button to the list
1. Consolidate GSoC 2020 and 2019. A single GSoC page should hold both 2020 and 2019 descriptions.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by RohitDhatrak** [comment]
I would like to work on this issue.

**Comment by Nikhil-Ladha** [comment]
> I would like to work on this issue.

Sure! Please go ahead with it. If stuck anywhere or want any help feel free to ping me in slack🙂

**Comment by kennyOlakunle** [comment]
Is this issue assigned to anyone yet??

**Comment by RohitDhatrak** [comment]
@kennyOlakunle yes I have started working on this

**Comment by kennyOlakunle** [comment]
Okay @RohitDhatrak, Well done.

**Comment by Sudhish2101** [comment]
Shall I start working on this?

**Comment by RohitDhatrak** [comment]
I won't be able to complete this because something came up @lolyparty you can assign this issue to @kennyOlakunle or @Sudhish2101

**Comment by Nikhil-Ladha** [comment]
Go ahead @Sudhish2101 . Its all yours now 🙂
