### ISSUE TITLE
Add Created By and Used By section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#331]
**Current State of the Meshery.io site**
There is no section that identifies Layer5 as the creator of Meshery. Nor is there a section that highlights users of Meshery.

**Desired State of the Meshery.io site**
Add a new section that contains two headings:

1. Created By
 - Layer5
2. Used By
 - see the list in the [ADOPTERS.md](https://github.com/layer5io/meshery/blob/master/ADOPTERS.md) file in the meshery repo.

**Design Inspiration**
from https://openebs.io
<img width="1258" alt="Screen Shot 2020-09-25 at 11 49 28 AM" src="https://user-images.githubusercontent.com/7570704/94294343-500b1d80-ff25-11ea-954e-32b04728470b.png">

from https://www.envoyproxy.io
<img width="1245" alt="Screen Shot 2020-09-25 at 11 50 57 AM" src="https://user-images.githubusercontent.com/7570704/94294414-6add9200-ff25-11ea-8b24-c33bd36c5bb4.png">

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by kishore007k** [comment]
I would like to work on this issue If it is still open.
