### ISSUE TITLE
Addition of better explanatory Comments in html files for easy and fast bug fixes.

### ISSUE THREAD

**Issue by prasanjit15** [layer5io/meshery.io#332]
It becomes very difficult to analyse each and every file without comments. So, to create a clean coding environment and also to help others to easily look into the section into which they have to make changes in order to fix the bugs, it is important to have comments.

**Comment by leecalcote** [comment]
Sounds great, @prasanjit15 👍

**Comment by leecalcote** [comment]
@prasanjit15 is this something that you would like to tackle?

**Comment by l5io** [comment]
Stale issue.
