### ISSUE TITLE
[Calendar] Create independent page for the new calendar

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#342]
**Current State of the Meshery.io site**
A new calendar provided in #340 has been incorporated into the community page.

**Desired State of the Meshery.io site**
This new calendar can be placed onto its own, standalone page as well at meshery.io/calendar.
The menu item for the calendar can be updated to point to this new page.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by Keenal** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
@Keenal That would great. 👍

**Comment by Keenal** [comment]
So I have been trying to install all the dependencies and I did not expect it to take so much time. I'm currently where I get this message "Your Ruby version is 2.7.2, but your Gemfile specified 2.7.0". Just wanted to let you know that I'm still working on it and if you have any quick ways of tackling that issue, please let me know, thanks!

**Comment by tripathyprateek** [comment]
Yes. This happens because the Ruby Bundler doesn't recognise the version. Try running `gem install bundler` to fix this issue. I think this might work.

**Comment by Keenal** [comment]
> Yes. This happens because the Ruby Bundler doesn't recognise the version. Try running `gem install bundler` to fix this issue. I think this might work.

![image](https://user-images.githubusercontent.com/14351534/95828873-81486380-0d03-11eb-8ac9-b89010fc9ce9.png)

Still getting the same error.

**Comment by Nikhil-Ladha** [comment]
Which OS are you using?
If linux, then change the version of ruby to 2.7.2 in Gemfile. Then run `bundle install`. Then, the `make site` command.

**Comment by Keenal** [comment]
Can you just change the version of Ruby in gemfile? Wouldn't that cause issues? There must be a reason why a certain version was set in the gemfile, right? Or would I be okay changing it?

**Comment by Nikhil-Ladha** [comment]
> Can you just change the version of Ruby in gemfile? Wouldn't that cause issues? There must be a reason why a certain version was set in the gemfile, right? Or would I be okay changing it?

That's the reason I asked you to do a bundle install after changing the version 🙂

**Comment by Keenal** [comment]
Oh, alright. It works if I change the version first and then do bundle install. And gotcha, I won't commit the gemfile changes, I hope that will not cause issues merging. Thank you!!

**Comment by Keenal** [comment]
Am I supposed to be getting this for make site command? 

![image](https://user-images.githubusercontent.com/14351534/95886868-276c8b80-0d4d-11eb-9116-0b7ff5485b3c.png)

**Comment by Keenal** [comment]
Yes, it did run successfully! 

![image](https://user-images.githubusercontent.com/14351534/95893821-33108000-0d56-11eb-9bf0-3a3f638daabc.png)

**Comment by Nikhil-Ladha** [comment]
Hmm...which os are you using and how have you set up ruby?
Then try changing the ruby version in your system to 2.7.0 only. Maybe that should fix as that is tested.
It looks like a dependency issue.

**Comment by PluckyPrecious** [comment]
Hey @Keenal how is this coming up

**Comment by Keenal** [comment]
> Hey @Keenal how is this coming up

Hey! I haven't had a chance to try it after my Ruby was giving me errors. I think I'll unassigned myself so someone else can work on it. Sorry about that!

**Comment by leecalcote** [comment]
@keenal, you can try make docker to circumvent your challenges with Ruby.

**Comment by Keenal** [comment]
Alright, I will try that! Also, has the application been deployed to Docker? Because that will also be easier for contributors to just build the whole application on their location machine and not have to worry about dependencies. I was just wondering about this.

**Comment by leecalcote** [comment]
@Keenal good call. Yes, it has. Actually, if you execute the command `make docker` from within the root of the fork of this this repo, it will build the site in docker. 👍

**Comment by Keenal** [comment]
Great, I will try that out then, thank you!

**Comment by Keenal** [comment]
Hey there, it's working!! I am finally able to see the site and I'll go ahead and make the changes related to this issue and create a PR soon after.

**Comment by leecalcote** [comment]
😁

**Comment by Keenal** [comment]
So I would like to get a clarification. Right now, when we click on Calendar, it takes us directly to Google Calendar. We want it to instead take us to meshery.io/Calendar? I can create html page that links to meshery.io/Calendar. What would you like me to put in there? Just a like that takes us to the Google Calendar? Sorry if I am asking too many questions, I would like to get a clear understanding before I submit a PR.

**Comment by Nikhil-Ladha** [comment]
I think you don't have to do any changes to the calendar, just create the new page and add this calendar on that page. Some design enhancements are always welcome if you want. 

In the current page, maybe we can remove the calendar and just add a callout to the calendar on the meshery.io/calendar page.

**Comment by leecalcote** [comment]
Minor issue - the menu item for the new calendar page should not be marked as external (should not carry an external link icon adjacent to it).

**Comment by nik-redhat** [comment]
@Keenal please add it the above comment to the new issue when you create one.
