### ISSUE TITLE
Update Brew mesheryctl installation instructions

### ISSUE THREAD

**Issue by clementkng** [layer5io/meshery.io#343]
**Current State:**
Currently, in the Getting Started page for Meshery (https://meshery.io/#getting-started), the Brew installation instructions are outdated. When you run them, you'll get an error since `mesheryctl` is not properly installed.

**Desired State:**
The instructions should be updated based on the instructions under the "Installing with Homebrew section" here: https://meshery.layer5.io/docs/installation

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Fahdmoh01** [comment]
Kindly assign me to this issue.

**Comment by Nikhil-Ladha** [comment]
Cool, go ahead with it @Fahdmoh01 :+1:
