### ISSUE TITLE
[DOC]The Helm v2 scripts in a wrong way and need to be fix 

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery.io#344]
**Current State:**

Going to the https://meshery.io/#getting-started and make a choice on Kubernetes platform, you will see that the helm v2 script of how to deploy Meshery with Helm v2

```
git clone https://github.com/layer5io/meshery.git; cd meshery
kubectl create namespace meshery
helm template meshery --namespace meshery install/kubernetes/helm/meshery
```

As we know if we use the `template` we just rendered the manifest and without deployment. Say in other word, the command just print the manifest and do nothing with deployment. 

**Desired State:**

There need to fix the issue and the reference address below https://meshery.layer5.io/docs/installation/platforms/kubernetes#helm-v2

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by iambami** [comment]
Hi Aisuko can you put me through this?

**Comment by Aisuko** [comment]
Any issue you hit?

**Comment by iambami** [comment]
I'd love to work on it

**Comment by iambami** [comment]
Can I chat you up on slack?

**Comment by Aisuko** [comment]
For sure

**Comment by akashgp09** [comment]
Can I take this issue or @iambami you are still up on it ?

**Comment by Aisuko** [comment]
> Can I take this issue or @iambami you are still up on it ?

Yes, please.
