### ISSUE TITLE
Add Ericsson's logo to the Used By section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#346]
**Current State of the Meshery.io site**
Ericsson is not listed as a user. See Meshery [ADOPTERS](https://github.com/layer5io/meshery/blob/master/ADOPTERS.md) file. 

**Desired State of the Meshery.io site**
Given use by employee's at Ericsson, add Ericsson's logo to those under the **Used By** section.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by leecalcote** [comment]
@akashprasher interested?

**Comment by akashprasher** [comment]
I can see a PR already coming. Please review it and it does work then it's good otherwise I'm open to this.
