### ISSUE TITLE
Navigation menu has transparent background in mobile view

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#35]
**Description**
The background of the dropdown navigation menu is transparent when users are on a mobile device or small screen width.

**Screenshot**
<img width="507" alt="Screen Shot 2019-12-02 at 8 12 43 AM" src="https://user-images.githubusercontent.com/7570704/70004495-543ff780-151b-11ea-976e-808901622f17.png">

**Expected Behavior**
The menu background should have a solid color.

**Comment by supra08** [comment]
Hi @leecalcote, I would like to take up this issue.

**Comment by leecalcote** [comment]
@supra08 awesome. Thank you for taking on this issue!

**Comment by leecalcote** [comment]
@supra08 crushed this one. Thank you, @supra08!
