### ISSUE TITLE
Add EnvoyFilter Provisioning as a feature to the documentation

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery.io#350]
**Desired State:**

We have introduced a new feature for meshery to configure a custom EnvoyFilter of their choice for the Istio service mesh. We should have them added to the main-page as well as the `/features` section.
Here is a sample screenshot that can be attached to describe the feature on meshery dashboard.
<img width="1792" alt="Screenshot 2020-10-16 at 6 44 40 PM" src="https://user-images.githubusercontent.com/10404724/96262614-a973e300-0fdf-11eb-927d-361a9e5b701c.png">

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by kumarabd** [comment]
@leecalcote  @chandrashritii This can be marked for `hacktoberfest` I believe. What say?

**Comment by iambami** [comment]
hi love to take this

**Comment by kumarabd** [comment]
@Nikhil-Ladha @chandrashritii  Is there someone who can help @iambami with this issue. She has a couple of queries around this issue, can any of you give her a little context on this?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha @chandrashritii Is there someone who can help @iambami with this issue. She has a couple of queries around this issue, can any of you give her a little context on this?

Yeah, @kumarabd. She approached me with some questions and I have guided her in possible ways. I think she is working on it now.

**Comment by kumarabd** [comment]
> > @Nikhil-Ladha @chandrashritii Is there someone who can help @iambami with this issue. She has a couple of queries around this issue, can any of you give her a little context on this?
> 
> Yeah, @kumarabd. She approached me with some questions and I have guided her in possible ways. I think she is working on it now.

@Nikhil-Ladha Thanks a lot  :)

**Comment by leecalcote** [comment]
All, the deadline on this update encroaches. We need this up with 12 hours from now.
