### ISSUE TITLE
Fix the Google calendar sync for Fullcalender

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/meshery.io#356]
**Description**

In the [community](https://meshery.io/community/) page of Meshery site, the Fullcalender is not syncing with the Google calendar API. This needs to be fixed.

**Useful Resources**
- [FullCalender Docs](https://fullcalendar.io/docs/v3/google-calendar)
- [Google API](https://github.com/layer5io/meshery.io/blob/fefecabbe833f0d806d121bd1f6172cc0923d849/community.html#L37) key. 

**Screenshots**

![fullcalendar](https://user-images.githubusercontent.com/48355572/96877505-5e524800-1497-11eb-9058-66cc7d3e88e9.JPG)

**Enviroment:**
 - OS: [e.g. Windows, Ubuntu]
 - Browser: [e.g. Chrome, Firefox]
 - Device: [e.g. laptop, Android]

---
[Optional] **To Reproduce**
1. Go to [community](https://meshery.io/community/)
3. Scroll down to the #Connect 
4. See error!

**Comment by jlcastrogro** [comment]
Hi, I want to work in this issue :)
How to I get the  correct key?

**Comment by PluckyPrecious** [comment]
Hi @jlcastrogro the API key is at the useful resources above.

**Comment by Neilblaze** [comment]
@jlcastrogro Sure! Go for it :+1: 
The api key is [here](https://github.com/meshery/meshery.io/blob/3bb19f5d7ea40552010009ffa0d3f460d659d02d/community.html#L37)

**Comment by jlcastrogro** [comment]
Hi, again @Neilblaze, I need the Meshery Community calendar to be public and its calendar ID, please:

![Screenshot_20201026_210726](https://user-images.githubusercontent.com/20060947/97252512-bbb80300-17cf-11eb-829c-a079a080959a.png)
![Screenshot_20201026_210758](https://user-images.githubusercontent.com/20060947/97252514-bfe42080-17cf-11eb-8969-c261ae413979.png)

**Comment by Neilblaze** [comment]
@chandrashritii ^^

**Comment by leecalcote** [comment]
@Neilblaze @jlcastrogro @chandrashritii the calendar is publicly shared. The integration ID is available in the original issue - https://github.com/meshery/meshery.io/issues/164#issuecomment-704530710

**Comment by leecalcote** [comment]
I'll paste the integration ID for convenience - meshery.io_eh2aa9dpf1g40elvoc762jnphs@group.calendar.google.com

**Comment by jlcastrogro** [comment]
@leecalcote @Neilblaze I don't know but with the Google API key and the calendar ID that you have provided me it does not work. I test a simple example with my Google Key and calendar ID and it is working. If the calendar ID is correct, I think that the Google API Key is the problem. Thanks.

**Comment by jlcastrogro** [comment]
@Neilblaze, Excuse me, who could check if the Google API gave me is correct?

**Comment by leecalcote** [comment]
@jlcastrogro I meant to message earlier. Here is a couple screenshots from the Google Cloud Console:

<img width="537" alt="Screen Shot 2020-10-29 at 8 41 41 PM" src="https://user-images.githubusercontent.com/7570704/97650543-ec927500-1a27-11eb-943e-46cfe3af4131.png">

<img width="567" alt="Screen Shot 2020-10-29 at 8 41 27 PM" src="https://user-images.githubusercontent.com/7570704/97650547-f025fc00-1a27-11eb-97eb-ebbf0d54e2a5.png">

We can temporarily remove the domain restriction as a test to see if that is getting in the way...

**Comment by jlcastrogro** [comment]
Excuse me, @leecalcote, I forgot about the domain, that is my error why it does not work in my local :p

**Comment by leecalcote** [comment]
😅 No problem. Very pleased that you're solving this issue.

**Comment by leecalcote** [comment]
@jlcastrogro you are most welcome to join the Meshery community here - http://slack.meshery.io - many resources and friendly people inside.

**Comment by jlcastrogro** [comment]
@leecalcote Can you remove the domain restrictions, please? A moment, just to test it.

**Comment by leecalcote** [comment]
Ok. Here we are:

<img width="1209" alt="Screen Shot 2020-10-29 at 9 08 32 PM" src="https://user-images.githubusercontent.com/7570704/97651756-eeaa0300-1a2a-11eb-92af-6024b9d76868.png">

**Comment by jlcastrogro** [comment]
![Screenshot_20201029_201239](https://user-images.githubusercontent.com/20060947/97652034-201ed080-1a23-11eb-9714-7f7129936d55.png)

@leecalcote It worked! ¡Hurra! :laughing:

**Comment by leecalcote** [comment]
jaja! It certainly felt like we had a few meetings. Yes, yes, we do have meetings. :)
