### ISSUE TITLE
[Feature] Add Meshery Adapter for NGINX Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#357]
**Current Behavior**
NGINX Service Mesh is missing. A new adapter has been created - https://github.com/layer5io/meshery-nginx-sm

**Desired Behavior**
- The supported service meshes table should have NGINX Service Mesh adapter listed as an alpha adapter.
- use the Nginx service mesh logo recently included in the https://layer5.io/landscape

<img width="602" alt="Screen Shot 2020-10-22 at 4 33 34 PM" src="https://user-images.githubusercontent.com/7570704/96932344-589f3700-1484-11eb-8810-6c5dd23eb030.png">

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by PluckyPrecious** [comment]
Ai ai Captain!
