### ISSUE TITLE
Fix: Misaligned Layout of the community /contributors page

### ISSUE THREAD

**Issue by kishore007k** [layer5io/meshery.io#362]
**Current State of the Meshery.io site**
1. The Community Page of the [Meshery.io](https://meshery.io/community/) site members have misaligned in the (1920 X 1080) resolution and for the 1625px and below it is aligned perfectly.

![issue-1](https://user-images.githubusercontent.com/34863222/97139838-61905100-1781-11eb-9d86-99d5361fafef.PNG)

2. Update the Community Members of the [Meshery.io](https://meshery.io/community/) site. Add the newly added members to the community page from [Layer5.io](https://layer5.io/community/members) site

**Desired State of the Meshery.io site**
1. Fix the layout of the Community members Page.
2. Add the newly added members to the Community Page

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.
- You can find the Members in [Community Members](https://github.com/layer5io/layer5/tree/master/collections/_members) of the Layer5
- The Community Members of the [Meshery.io](https://meshery.io/) site is located in [Community Members](https://github.com/layer5io/meshery.io/tree/master/collections/_contributors).

**Comment by PluckyPrecious** [comment]
I could get my hands on this.😇

**Comment by kishore007k** [comment]
@PluckyPrecious No, I have some other Issue that I have been working on.

**Comment by PluckyPrecious** [comment]
Very well then, I’ll take it up.👍🏽

**Comment by kishore007k** [comment]
Awesome 🔥 @PluckyPrecious
