### ISSUE TITLE
Add a call for Adopters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#366]
**Current State of the Meshery.io site**
The Created By and Used By section of the site has a list of logos, but does not call for others to add their logo.

**Desired State of the Meshery.io site**
Add a call to action like "Add yourself as an adopter... and share your service mesh story with the community".

<img width="354" alt="Screen Shot 2020-10-29 at 4 25 58 PM" src="https://user-images.githubusercontent.com/7570704/97634429-b04d1d80-1a03-11eb-8bdc-bc4c82345220.png">

Button should link to https://github.com/layer5io/meshery/blob/master/ADOPTERS.md

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by jlcastrogro** [comment]
Can I try to do this?

**Comment by leecalcote** [comment]
@jlcastrogro, yes, that would be great. 👍

**Comment by jlcastrogro** [comment]
![Screenshot_20201030_133531](https://user-images.githubusercontent.com/20060947/97749519-ce268b00-1ab4-11eb-9280-91e776b44f6b.png)
![Screenshot_20201030_134115](https://user-images.githubusercontent.com/20060947/97750014-a71c8900-1ab5-11eb-8be7-170540f262c3.png)

Is it ok like this?

**Comment by leecalcote** [comment]
I'm having a hard time complaining about any of this, @jlcastrogro. It looks pretty good. You might consider a small reduction of font size on the call to action, understanding that the vast majority of site visitors won't be taking this action, so it doesn't need to be the most visible action item.

**Comment by jlcastrogro** [comment]
@leecalcote I will look it.

**Comment by jlcastrogro** [comment]
@leecalcote better or more bigger or very small? I'm not good at the front, sorry.
![imagen](https://user-images.githubusercontent.com/20060947/97779370-2c9a4a80-1b43-11eb-829e-37171077aa26.png)

**Comment by leecalcote** [comment]
Nice! Looking good. 😀
