### ISSUE TITLE
Add dedicated page for community calendar

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#368]
**Current Status:**
1. A community calendar is available and located on the latter half of the community page.
1. A menu item for the community calendar exists, but points to the google calendar directly.
1. Some issues exists with the mobile view of the calendar.

**Desired Status:**
1. create a new page, dedicated to the display of the community calendar. Include a link to allow people to subscribe to the calendar (https://bit.ly/2SbrRhe)
1. update the "calendar" menu item to point to a new page that only has the calendar on it? The calendar can still be shown on the community page, too.
1.  improve the responsiveness of the calendar.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery.io/pull/367#issuecomment-719591673_

**Comment by leecalcote** [comment]
// @jlcastrogro

**Comment by jlcastrogro** [comment]
@leecalcote, nice, nice :+1:

**Comment by jlcastrogro** [comment]
@leecalcote Is there a difference between point 1 with the issue #342?

**Comment by leecalcote** [comment]
@jlcastrogro, yes, those two statements:

"This new calendar can be placed onto its own, standalone page as well at meshery.io/calendar.
The menu item for the calendar can be updated to point to this new page."

Are intended to mean that the calendar can be exposed in two places on the site - where it is today, and also, on it a page dedicated to the community calendar.

**Comment by Nikhil-Ladha** [comment]
I think only point 3 is left now and just this [comment](https://github.com/meshery/meshery.io/issues/342#issuecomment-723062882) needs to be addressed.

**Comment by jlcastrogro** [comment]
@Nikhil-Ladha I think the same. I will check it. The problems are with the mobile version, right?

**Comment by Nikhil-Ladha** [comment]
Mobile version, and the design can be improved a bit.
