### ISSUE TITLE
Migrate all meshery.layer5.io/docs references to docs.meshery.io

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery.io#380]
**Description**
The domain name used for publishing Meshery's documentation has changed from "https://meshery.layer5.io/docs" to "https://docs.meshery.io".

**Expected Behavior**
All references to "https://meshery.layer5.io/docs" need to be updated to "https://docs.meshery.io".

**Comment by kumarabd** [comment]
@chandrashritii Something quick that can be done, docs.meshery.io is already up

**Comment by leecalcote** [comment]
Done
