### ISSUE TITLE
[Site] Insert comma into thousandths place for number of tests run

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#381]
**Current Behavior**
Just like the https://layer5.io/meshery site has the number of performance tests run with a comma inserted into the thousandths place, so too should the perf test number on the smp-spec site have a comma.

<img width="641" alt="Screen Shot 2020-11-18 at 9 22 21 AM" src="https://user-images.githubusercontent.com/7570704/99557058-dec97300-2987-11eb-94df-d5001f319135.png">

<img width="1035" alt="Screen Shot 2020-11-18 at 10 22 02 AM" src="https://user-images.githubusercontent.com/7570704/99557106-ebe66200-2987-11eb-92bf-b83d9a8b5cbf.png">

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by jomefavourite** [comment]
I'll like to do this

**Comment by leecalcote** [comment]
Perfect, @jomefavourite 👌

**Comment by leecalcote** [comment]
Assuming success on Meshery.io, there is a very similar issue open on SMP-spec.io, too

**Comment by jomefavourite** [comment]
> Assuming success on Meshery.io, there is a very similar issue open on SMP-spec.io, too

Okay, I'll check it out.

**Comment by jomefavourite** [comment]
I'm sorry I couldn't find SMP-spec.io, is it a repository?

**Comment by jomefavourite** [comment]
> I'm sorry I couldn't find SMP-spec.io, is it a repository?

I'm guessing its service-mesh-performance right?
