### ISSUE TITLE
[Traefik Mesh] Adapter and Repo name change

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#387]
**Current State:**
The Maesh project underwent a name change and is now referred to as "Traefik Mesh".

**Desired State:**
The Meshery site needs updated to reflect this project name change.

The GitHub repository for Meshery Adapter for Traefik Mesh has also recently been updated. All links to https://github.com/layer5io/meshery-maesh need to be updated to https://github.com/layer5io/meshery-traefik-mesh

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by leecalcote** [comment]
Helloooo @pjzzz.... this one has your name on it. 😄

**Comment by pjzzz** [comment]
Yeah😊 On it.

**Comment by pjzzz** [comment]
@leecalcote I remember you mentioning Traefik Mesh is in Beta. Should I change it from alpha to beta here as well?

**Comment by leecalcote** [comment]
@pjzzz, yes, please. That would be great.
