### ISSUE TITLE
[Chart] The version of chart should be add to this repo

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery.io#391]
I already fix the issue on meshery chart and need to update the new version to https://artifacthub.io/packages/helm/meshery/meshery

**Comment by Aisuko** [comment]
The resource https://github.com/meshery/meshery.io/tree/master/charts

**Comment by Aisuko** [comment]
@zjyingchang

**Comment by zjyingchang** [comment]
> @zjyingchang Would you like this one?


Yeah! I can try it.

**Comment by leecalcote** [comment]
@zjyingchang excellent. 👍 

@Aisuko, hopefully, we'll get to a point where this is automated (https://github.com/meshery/meshery/issues/2278). What do you think?
