### ISSUE TITLE
Email Address input is not aligned

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/meshery.io#393]
**Description**

Email input is not correctly aligned 

**Expected Behavior**

Email must be aligned with Name input

**Screenshots**
Add screenshots, if applicable, to help explain your problem.
![Screenshot_2021-01-24 Meshery The Service Mesh Manager](https://user-images.githubusercontent.com/44670961/105623699-9aec6180-5e41-11eb-838c-83c39795dd5b.png)

**Comment by leecalcote** [comment]
Good eye, @chinmaym07!
