### ISSUE TITLE
[Adopters] Add MetaBob to the list of adopters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#396]
**Current State of the Meshery.io site**
MetaBob is a Meshery user, but not listed on the meshery.io site.

**Desired State of the Meshery.io site**
MetaBob should be listed in the USED BY section of the site.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by leecalcote** [comment]
// @sakomws

**Comment by leecalcote** [comment]
@chinmaym07 would you like to take this on?

// @Jashpatel1

**Comment by chinmaym07** [comment]
Yes @leecalcote sir .I can do that. 👍🏻
