### ISSUE TITLE
Footer needs improvement

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#4]

**Comment by gunjanmimo** [comment]
Sir, may you elaborate on the description of expected footer behavior?

**Comment by leecalcote** [comment]
@gunjanmimo yes.... see #1, if you would.

**Comment by leecalcote** [comment]
@dhruv0000 would you like to give this a shot, using layer5.io's footer as inspiration?

**Comment by dhruv0000** [comment]
Sure @leecalcote . I assume we want the same data as in `layer5.io/meshery`'s footer?
