### ISSUE TITLE
Instructions for installing via Scoop

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#400]
**Current State of the Meshery.io site**
`mesheryctl` is available via Scoop as a Windows-based package manager.
The meshery.io site doesn't provide users the option of using Scoop to install Meshery.

<img width="1064" alt="Screen Shot 2021-02-19 at 5 39 06 PM" src="https://user-images.githubusercontent.com/7570704/108573290-d57ada00-72d9-11eb-8794-91cf50d97251.png">

**Desired State of the Meshery.io site**
Scoop should be listed as an option under the Windows section. See this repo as a resource - https://github.com/layer5io/scoop-bucket and the https://docs.meshery.io site.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by leecalcote** [comment]
@metonymic-smokey interested in picking this up?

**Comment by metonymic-smokey** [comment]
@leecalcote ,
Yes! Give me a week to submit a PR.

Thanks for the consideration!

**Comment by leecalcote** [comment]
Sounds real good. You bet. 👍
