### ISSUE TITLE
Subscribe button is missing alignment & Vertically Align Community & image

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/meshery.io#404]
**Description**

 Subscribe button is missing alignment wrt to name,email inputs  & Service mesh landscape button is having width issue.
Vertically Align Community & image wrt to text.

**Screenshots**

![Screenshot_2021-02-22 Meshery The Service Mesh Manager](https://user-images.githubusercontent.com/44670961/108680594-13fbd900-7514-11eb-9eae-3f7bec1359d4.png)
![Screenshot_2021-02-22 Meshery The Service Mesh Manager(2)](https://user-images.githubusercontent.com/44670961/108680605-178f6000-7514-11eb-8a57-c58fa10e95ad.png)
![Screenshot_2021-02-26 Meshery The Service Mesh Manager](https://user-images.githubusercontent.com/44670961/109346804-37b67a80-7898-11eb-8f1e-e5fbf5190339.png)

[Optional] **Additional Context**
After vertically aligning the image & Community Heading It looks like below.

![Screenshot_2021-02-22 Meshery The Service Mesh Manager(1)](https://user-images.githubusercontent.com/44670961/108680836-5e7d5580-7514-11eb-864d-2669dea0e5c8.png)

**Comment by leecalcote** [comment]
Thank you, @chinmaym07
