### ISSUE TITLE
[Docs] Extra rows in mesheryctl command reference table

### ISSUE THREAD

**Issue by metonymic-smokey** [layer5io/meshery.io#407]
**Description**
1. When building the site locally, there are some extra blank lines below commands, when the only change being made is adding a `channel.yaml` file for the specific command in `docs/_data/mesheryctlcommands/lifecycle/subcommands`.
2. [This page](https://docs.meshery.io/reference/mesheryctl) of the official site too shows the same issue below the `verbose` command.

**Expected Behavior**
The blank lines between commands should not be present.

**Screenshots**
1. When built locally(below `channel` and `completion`):
![image](https://user-images.githubusercontent.com/48997495/109922725-d5b8a380-7ce3-11eb-9b06-e5031876a4c7.png)

2. From the website:
![image](https://user-images.githubusercontent.com/48997495/109922671-be79b600-7ce3-11eb-938d-37e8b5f9b1a0.png)

**Enviroment:**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest
 - Device: laptop

**Comment by leecalcote** [comment]
Thank you for opening this up, @metonymic-smokey. Is this an issue that you would like to address (take assignment of)?

**Comment by metonymic-smokey** [comment]
@leecalcote I think we now know the root cause of this issue(thanks to @alonsolopezr!) so this can be closed?
Maybe let's add a line to the Documentation Contribution section stating files must be checked for newlines when adding new commands?

Thanks!

**Comment by leecalcote** [comment]
Very good. 🙂 yes, that sounds about right. 👍
