### ISSUE TITLE
[Menu] Change "Mailing List" link to be local to site

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#408]
**Current State of the Meshery.io site**
The link in the screenshot points to layer5.io/subscribe

**Desired State of the Meshery.io site**
The link in the screenshot should point to meshery.io/subscribe

<img width="305" alt="Screen Shot 2021-03-20 at 11 26 27 PM" src="https://user-images.githubusercontent.com/7570704/111893864-e5b6cf80-89d3-11eb-9be8-883cdcbde7d6.png">

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by igallup** [comment]
Hi, could I take a crack at this one?

**Comment by leecalcote** [comment]
Hi @igallup, yes, that'd be great. 👍
