### ISSUE TITLE
[Homepage] Adding CNCF Landscape to Meshery Home page

### ISSUE THREAD

**Issue by austinogiza** [layer5io/meshery.io#410]
#### Current Behavior
We currently have no section highlighting Meshery as proudly representing service mesh management in the CNCF Landscape.

#### Desired Behavior
It will be good to created a new section, adding the CNCF landscape in Meshery home page

![mesh-](https://user-images.githubusercontent.com/44683018/111815538-16b3d900-88dc-11eb-8b7f-24e407ab741b.PNG)

Below is the design file 
https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1060%3A8

Below is the landscape svg
https://drive.google.com/file/d/1OtpsBtFesYT0FvpzlvK2KEqcJrgQC-k5/view?usp=sharing

**Comment by leecalcote** [comment]
@austinogiza please point to the CNCF Landscape SVG to be used.

**Comment by Lezette** [comment]
@austinogiza what section on the Homepage should this be on?

**Comment by austinogiza** [comment]
@Lezette  this should be after the Community and GSOD section

**Comment by Lezette** [comment]
@leecalcote I would like to work on this
