### ISSUE TITLE
Mailing lists update

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#416]
**Current State of the Meshery.io site**
Meshery has a couple of mailing lists:

https://groups.google.com/a/meshery.dev/g/community
https://groups.google.com/a/meshery.dev/g/dev
https://groups.google.com/a/meshery.dev/g/user

**Desired State of the Meshery.io site**
The https://meshery.io/subscribe page should have a link and short description of each.

The form on the page now is for the layer5.io mailer. It needs to stay, but these other three can be added. They won’t be forms, just links to groups.google.com

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by austinogiza** [comment]
Design specification over here https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1164%3A6564

<img width="1440" alt="meshery subscribe" src="https://user-images.githubusercontent.com/44683018/112696769-b8ac6600-8e86-11eb-96cb-64891bf1b7b3.png">

**Comment by Lezette** [comment]
@leecalcote I would like to work on this issue

**Comment by leecalcote** [comment]
@Lezette, that would be excellent. 👍
