### ISSUE TITLE
[Footer] Adding Layer5 as the creator of meshery to the footer

### ISSUE THREAD

**Issue by austinogiza** [layer5io/meshery.io#417]
**Current State:**
We current have only navlinks highlighting just Layer5 as the creator of meshery

**Desired State:**
Adding Layer5 as the creator of Meshery to the footer of  Meshery

Below is the desired design and the design link

https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1165%3A1044

<img width="346" alt="footer" src="https://user-images.githubusercontent.com/44683018/112701527-2e1d3400-8e91-11eb-940d-579c7c0bf326.png">

Here is the link to the Layer5 logo
https://drive.google.com/file/d/1A3A-YNkM5Ak9tVcM1Ryu_c3paEQiIggw/view?usp=sharing

**Comment by leecalcote** [comment]
Another, generally available link to logo - https://layer5.io/brand

**Comment by mahryam** [comment]
I would like to take this up.

**Comment by Thea10** [comment]
@Ruth-ikegah assign this to me please

**Comment by Ruth-ikegah** [comment]
sure!

**Comment by adithyaakrishna** [comment]
Hey @Thea10 any Progress here? 👀
