### ISSUE TITLE
Smooth Transition of Instruction section 

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/meshery.io#420]
**Current State of the Meshery.io site**
Instructions Section is neither opening smoothly nor closing. 

**Desired State of the Meshery.io site**

Smooth opening/closing of Instructions section in [meshery.io](https://meshery.io/)

https://user-images.githubusercontent.com/44670961/113330128-08ce7100-933c-11eb-9a0e-241b02572d81.mp4

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by leecalcote** [comment]
Good one, @chinmaym07 👍

**Comment by rijusougata13** [comment]
can you assign me?

**Comment by leecalcote** [comment]
@rijusougata13, if you would like to pick this one up, you're most welcome to it.

**Comment by rijusougata13** [comment]
yeah i would like to.but i'm having some problems when running ```make site```...i am trying to solve that problem

**Comment by leecalcote** [comment]
@rijusougata13 Ok, understood. Have you joined the Meshery Community - http://slack.meshery.io? Many helpful MeshMates in there that can point out resources for Jekyll. I assume you're having this challenge on Windows.

**Comment by rijusougata13** [comment]
> @rijusougata13 Ok, understood. Have you joined the Meshery Community - http://slack.meshery.io? Many helpful MeshMates in there that can point out resources for Jekyll. I assume you're having this challenge on Windows.

 yeah joining this group.. having problem in ubuntu

**Comment by rijusougata13** [comment]
@chinmaym07  PTAL .
