### ISSUE TITLE
Blurry CNCF Landscape image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#426]
**Description**
On the main meshery.io page, this image (in the screenshot) is rastered (a PNG) and will expand to a larger size that 100%, so it shows as blurry on large screens.

**Expected Behavior**
Use the SVG version of this logo: https://raw.githubusercontent.com/cncf/artwork/master/other/cncf-landscape/horizontal/color/cncf-landscape-horizontal-color.svg

**Screenshots**
Blurry.
<img width="818" alt="Screen Shot 2021-04-13 at 7 47 05 AM" src="https://user-images.githubusercontent.com/7570704/114554689-9d827a00-9c2c-11eb-9647-d5434557a4a2.png">

**Comment by imraghav20** [comment]
Hi @leecalcote 
Can I work on this issue?

**Comment by leecalcote** [comment]
Thanks for volunteering, @imraghav20. Yes, that would be great.

**Comment by imraghav20** [comment]
Should I replace the current image file with the new one?
Or I should keep both of them and instead change `<img src>` url?

**Comment by leecalcote** [comment]
Good of you to ask. I'm just realizing that the current image is an SVG already and that the CSS used on the tag `max-width` is just fine. 

So, I suspect the reason that it is blurry is because and imgbot came by and in the process of trying to reduce the size of the SVG, the imgbot compressed the original SVG and produced this blurry version.

So, in order to fix this issue, you can take a fresh copy of the SVG (linked above) and replace the existing SVG with this new one. I _think_ that's all that needs to be done.

**Comment by imraghav20** [comment]
Ok, thanks.
