### ISSUE TITLE
[Feature] - Add SMI Conformace to the Meshery Site Footer

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/meshery.io#431]
**Current State of the Meshery.io site**
The footer of [meshery.io](https://meshery.io) site does not have any link to [meshery.io/smi](https://meshery.io/smi) and hence a new link should be added here to direct to the SMI Page

**Existing:**
![image](https://user-images.githubusercontent.com/23498248/115951406-369f7380-a4fe-11eb-9121-be76d273fcea.png)

**Desired State of the Meshery.io site**
A Link to SMI Conformance to be added,

**Desired:**
![image](https://user-images.githubusercontent.com/23498248/115951522-c5ac8b80-a4fe-11eb-8cfd-4dea8a0211a3.png)

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by adithyaakrishna** [comment]
Assigning Myself on this 🎉

**Comment by leecalcote** [comment]
😄
