### ISSUE TITLE
[Docs] - Add Entry for Meshery Release Update

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/meshery.io#434]
**Current State:** The below image shows, we do not have v0.5.2
![image](https://user-images.githubusercontent.com/23498248/116229467-2b557d80-a774-11eb-97f7-b1d04840c541.png)

**Desired State:**
A new version, v0.5.2 has to be updated along with the link to the release

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by adithyaakrishna** [comment]
Wrong Repo :/

**Comment by leecalcote** [comment]
FYI

<img width="332" alt="Screen Shot 2021-04-27 at 5 52 37 AM" src="https://user-images.githubusercontent.com/7570704/116230066-d0dd0280-a71c-11eb-8bd5-57a4053a76ad.png">

**Comment by adithyaakrishna** [comment]
Ohh, I didn't know about this feaure, Thanks @leecalcote 🎉
