### ISSUE TITLE
[Site] Mailing lists: Add links to user and dev groups

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#435]
**Current State of the Meshery.io site**
Two of the the mailing lists at the bottom of meshery.io need their hyperlinks updated.

**Desired State of the Meshery.io site**
- User List - https://groups.google.com/a/meshery.io/g/user-group
- Dev List - https://groups.google.com/a/meshery.io/g/dev-group

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by marcocosta1618** [comment]
Hi, maybe I can help with this one. Can I take it?

**Comment by leecalcote** [comment]
Sounds great, @marcocosta1618. 👍

**Comment by marcocosta1618** [comment]
Great, thanks.
