### ISSUE TITLE
Increase the width of the performance tests run card

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/meshery.io#439]
**Description**

Text is overflowing on mobile view. 

**Expected Behavior**

Text should remain inside card on mobile view.
Increase the Width of the card to rectify this.

**Screenshots**

![Screenshot_2021-05-02 Meshery The Service Mesh Manager](https://user-images.githubusercontent.com/44670961/116816366-46166080-ab7f-11eb-86d2-ac261a112b55.png)

**Comment by samirparhi-dev** [comment]
I am willing to take this up.

**Comment by Anita-ihuman** [comment]
Sure @samirparhi-dev  go ahead
