### ISSUE TITLE
Extraneous ">" near screenshots

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#44]
**Description**
Errant "<" and ">" are visible next to most of the screenshots on the main meshery.io page.

<img width="587" alt="Screen Shot 2019-12-19 at 5 43 08 PM" src="https://user-images.githubusercontent.com/7570704/71218480-43b3af00-2287-11ea-8ad4-af5948b0120b.png">

**Comment by ashiscs** [comment]
Sir, in which file do i need to make change?

**Comment by leecalcote** [comment]
Hi @ashiscs, there are a number of these accidental ">" and "/>" that need to be removed inside the [index.html](https://github.com/layer5io/meshery.io/blob/master/index.html).

**Comment by ashiscs** [comment]
Sir @leecalcote ,yeah i removed 4 of them.

**Comment by leecalcote** [comment]
Oh, very good. I didn't realize that you had already submitted a PR. Looks great.

**Comment by ashiscs** [comment]
Thank you sir @leecalcote
