### ISSUE TITLE
[Feature] [Configuration Card][Operator Users]  CloudEvents specification

### ISSUE THREAD

**Issue by rav121** [layer5io/meshery.io#443]
#### Current Behavior

https://meshery.io/features --> Configuration Card--> does not mention using CloudEvents

#### Desired Behaviour

https://meshery.io/features 
Use Existing card: [Feature] [Configuration] or a new card  [Feature][Configuration] [Operator Users]
Add  items: Management of task/operation lifecycle for Operators Actors using CloudEvents specification
Beautify/Rephrase "Operatore with best practices"
#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
We are in need of a short blurb on the project site that describes the fact that Meshery generates and consumes CloudEvents compatible events.

**Comment by kartike66** [comment]
I'm working on this issue.
thanks
