### ISSUE TITLE
Lil issue in the meshry docs

### ISSUE THREAD

**Issue by Jassi10000** [layer5io/meshery.io#451]
**Description**
A brief description of the issue.

 Issue already opened at          
https://github.com/layer5io/meshery/issues/2879

**Expected Behavior**
A brief description of what you expected to happen.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

Apologies for opening it in the wrong repo

**Comment by leecalcote** [comment]
Docs are in the Meshery repo. This repo contains the project site only.

**Comment by leecalcote** [comment]
You can close this issue.

**Comment by Jassi10000** [comment]
Actually Mr. Samir told me that docs are in meshery.io   not meshery
