### ISSUE TITLE
[Docs][Meshery.io] Update Link to meshery releases on meshery.io for windows user

### ISSUE THREAD

**Issue by piyushsingariya** [layer5io/meshery.io#453]
**Desired State:**
Currently, the link redirect us to- https://github.com/layer5io/meshery/releases/tag/v0.3.9
Change it to (https://github.com/layer5io/meshery/releases/)
Plus also update the command to `mesheryctl system start` from `./mesheryctl system start`

![image](https://user-images.githubusercontent.com/50979887/117420731-7a9d6a00-af3b-11eb-8677-9e7cdbe45438.png)
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by soham4abc** [comment]
working on it

**Comment by soham4abc** [comment]
This issue is already resolved
