### ISSUE TITLE
Windows logo not visible

### ISSUE THREAD

**Issue by Naimaoye** [layer5io/meshery.io#469]
**Description**
Windows logo not visible

**Expected Behavior**
Windows logo expected to be visible just like other icons

**Screenshots**
![image](https://user-images.githubusercontent.com/48380183/119906018-479c3400-bf45-11eb-814d-418036344049.png)

**Comment by Ayush-Khandelwal-007** [comment]
Hey @Naimaoye Could you please specify the device and browser in use while you are facing this issue.

**Comment by leecalcote** [comment]
I see it in Safari 14.1 on macOS Big Sur 11.3.1 at https://meshery.io/#getting-started

**Comment by leecalcote** [comment]
This needs to be fixed urgently.

**Comment by texas2010** [comment]
@leecalcote, I was going to send PR but you got it.  oops haha.

**Comment by leecalcote** [comment]
Oh, no! Ha!

Good news, though: there are plenty more where this comes from - https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+

**Comment by texas2010** [comment]
@leecalcote, that is fine. Thank you for the link. I will check it out.

Btw I saw the open job at your company. I will send my resume to that email later.

Have a nice day!

**Comment by leecalcote** [comment]
Excellent. 😄
