### ISSUE TITLE
[README] Need to add `Community Forum`

### ISSUE THREAD

**Issue by amino19** [layer5io/meshery.io#474]
**Description**

<a href="https://github.com/layer5io/meshery.io/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123441080-16209200-d5f1-11eb-8cac-0f82770161e6.png)

**Desired behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123440623-9d213a80-d5f0-11eb-8ffd-87ba14c0159b.png)

**Note:**
Need to add only last line for `Community Forum`

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
**Reference:**
- Take reference to this <a href="https://github.com/layer5io/layer5/pull/1949">pull request</a>

**Comment by NikhilSharma03** [comment]
@amino19 Can I work on this?

**Comment by amino19** [comment]
@NikhilSharma03 : Good to see that, already done! Thanks. 😉
