### ISSUE TITLE
Update copyright information in the footer

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery.io#477]
**Current State of the Meshery.io site**
The footer of the website says "© 2021 Layer5, Inc." -

![Screenshot_20210627_202333](https://user-images.githubusercontent.com/49474499/123549258-d0490280-d785-11eb-92ce-a2e01d1d4a93.png)

**Desired State of the Meshery.io site**
It should instead say "© 2021 The Meshery Authors"

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

**Comment by pottekkat** [comment]
Fixed in commit https://github.com/meshery/meshery.io/commit/a76124cff584d3b1af942a88ba90537b84f052a7
