### ISSUE TITLE
Site menu overhaul

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#56]
**Current Behavior**
The current menu has "GitHub" listed, but is missing Slack, the mailing list, community drive, community calendar and so on.

**Desired Behavior**
New top-level menu items with sub-items structured like so:

[Docs](https://meshery.layer5.io/docs)

[Community](/community)

[Blog](https://layer5.io/blog)

Connect
- [Calendar](https://layer5.io/subscribe/)
- [GitHub](https://github.com/layer5io/meshery)
- [Mailing List](https://layer5.io/subscribe/)
- [Slack](http://slack.layer5.io)

Resources
- [Branding](https://layer5.io/brand#meshery)
- [Code of Conduct](https://github.com/layer5io/meshery/blob/master/CODE_OF_CONDUCT.md)
- [Contributing](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md)

[Run Meshery](#getting-started)

**Comment by ashiscs** [comment]
@leecalcote sir, can you elaborate this issue?

**Comment by leecalcote** [comment]
@ashiscs good question. I've updated the description of the issue. Does this help?

**Comment by l5io** [comment]
Let's be consistent and reuse the same menu javascript/html from layer5.io here on meshery.io.

**Comment by leecalcote** [comment]
Thank you for triaging issues, @ashiscs 👍
