### ISSUE TITLE
Include Citrix logo for CPX adapter listing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#59]
**Current Behavior**
The CPX entry in the list of adapters is missing a logo.
![Screen Shot 2019-12-27 at 7 45 24 AM](https://user-images.githubusercontent.com/7570704/71519392-fcc44b80-287c-11ea-9c90-efb19d4ef040.png)

**Desired Behavior**
The Meshery adapter for CPX should have a logo akin to that of the other adapters.

**Comment by ashiscs** [comment]
This issue is resolved by pr no #61 .
So, it needs to be closed.
