### ISSUE TITLE
Optimized images make the static resource smaller file sizes without sacrificing quality.

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery.io#75]
**Current Behavior**
A brief description of what the problem is. (e.g. I need to be able to...)
There are not any optimized images.

**Desired Behavior**
A brief description of the enhancement.

Every PR which includes the static sources it can be optimized.

Please kindly take a look at https://github.com/Aisuko/meshery.io/pull/1 and I believe that feature is very fit with the project type like this. So, please add the ImgBot to our project [meshery.io](https://github.com/layer5io/meshery.io) 

---
[Optional] **Alternatives**
A brief description of any alternative solutions or features you've considered.

[Optional] **Additional context**

1, The address of ImgBot https://github.com/marketplace/imgbot 
2, Please just take the free open source plan. And it will be fit for us well.

**Comment by leecalcote** [comment]
Sounds real good, @Aisuko. Let's give it a shot. Looking over your example PR, it optimizes the images and displaces the existing images conveniently inline.
