### ISSUE TITLE
Add clipboard button capability to Kubernetes install commands

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery.io#99]
**Current Behavior**
The terminal commands for installing Meshery are missing the convenience of having the copy-to-clipboard function.

**Desired Behavior**
Each of the installation steps should have this easy-to-use function.

**Screenshot**
<img width="1114" alt="Screen Shot 2020-02-12 at 10 20 06 PM" src="https://user-images.githubusercontent.com/7570704/74401161-10ece980-4de6-11ea-9e51-7960198a5c29.png">

**Comment by gunjanmimo** [comment]
@leecalcote sir this problem is solved https://github.com/meshery/meshery.io/pull/107

**Comment by leecalcote** [comment]
fixed by #110
